Repository openeuropa/bootstrap-component-library, pull requests merged in 2021-07, with the labels that each got.

#8 feat(drupal-attributes): Drupal attributes for multiple components - FRONT-2408
  src/components/blockquote/blockquote.html.twig
  src/components/blockquote/blockquote.test.js
  src/components/button/__snapshots__/button.test.js.snap
  src/components/button/button.story.js
  src/components/button/button.test.js
  src/components/header/__snapshots__/header.test.js.snap
  src/components/icon/icon.html.twig
  src/components/link/__snapshots__/link.test.js.snap
  src/components/link/link.html.twig
  src/components/link/link.story.js
  src/components/link/link.test.js
  src/components/modal/__snapshots__/modal.test.js.snap
  src/components/modal/modal.html.twig
  src/components/spinner/spinner.html.twig
  src/components/spinner/spinner.test.js
  src/components/table/table.html.twig
  src/components/table/table.test.js
  src/data/blockquote/data.js
  src/data/button/spinnerData.js
  src/data/header/data.js
  src/data/icon/data.js
  src/data/modal/data.js
  src/data/pagination/dataCustomIcons.js
  src/data/spinner/data.js
  src/data/table/data.js
Labels: tag: new feature

#7 feat(button-drupal): Refactor button using drupal attributes - FRONT-2371
  src/components/accordion/__snapshots__/accordion.test.js.snap
  src/components/accordion/accordion.html.twig
  src/components/alert/alert.story.js
  src/components/alert/alert.test.js
  src/components/button/button.html.twig
  src/components/button/button.story.js
  src/components/button/button.test.js
  src/components/carousel/carousel.html.twig
  src/components/dropdown/__snapshots__/dropdown.test.js.snap
  src/components/dropdown/dropdown.html.twig
  src/components/link/link.story.js
  src/components/list-group/__snapshots__/list-group.test.js.snap
  src/components/list-group/list-group.html.twig
  src/components/navbar/__snapshots__/navbar.test.js.snap
  src/components/navigation/__snapshots__/navigation.test.js.snap
  src/components/offcanvas/offcanvas.html.twig
  src/components/toasts/toasts.html.twig
  src/data/alert/data.js
  src/data/button-group/data.js
  src/data/button-group/toolbarData.js
  src/data/button/data.js
  src/data/button/popoverData.js
  src/data/button/spinnerData.js
  src/data/button/toggleData.js
  src/data/button/tooltipData.js
  src/data/dropdown/data.js
  src/data/form/data-disabled.js
  src/data/form/data-grid.js
  src/data/form/data-horizontal.js
  src/data/form/data-inline.js
  src/data/form/data.js
  src/data/list-group/actionableData.js
  src/data/navbar/data.js
  src/data/navigation/dataTabs.js
  src/themes/default/scss/_icon.scss
  tools/story-utils/index.js
Labels: tag: new feature

#9 feat(drupal-link): Refactor link component - FRONT-2417
  src/components/dropdown/dropdown.html.twig
  src/components/header/__snapshots__/header.test.js.snap
  src/components/link/__snapshots__/link.test.js.snap
  src/components/link/link.html.twig
  src/components/link/link.story.js
  src/components/link/link.test.js
  src/components/list-group/__snapshots__/list-group.test.js.snap
  src/components/list-group/list-group.html.twig
  src/components/navbar/__snapshots__/navbar.test.js.snap
  src/components/navigation/__snapshots__/navigation.test.js.snap
  src/components/navigation/navigation.html.twig
  src/data/breadcrumb/data.js
  src/data/header/data-ecl.js
  src/data/header/data.js
  src/data/link/data.js
  src/data/link/toggleData.js
  src/data/link/tooltipData.js
  src/data/list-group/actionableData.js
  src/data/navbar/data.js
  src/data/navigation/dataTabs.js
Labels: tag: new feature

#6 chore: Adding bcl-builder package
  .gitignore
  CHANGELOG.md
  README.md
  babel.config.js
  bootstrap/package.json
  builder/bin/build.js
  builder/package.json
  builder/scripts/copy.js
  builder/scripts/scripts.js
  builder/scripts/styles.js
  docs/packages.md
  package.json
  src/components/alert/alert.story.js
  src/components/bcl-twig-templates/package.json
  src/themes/default/bcl-builder.config.js
  src/themes/default/icons/bootstrap-icons.svg
  src/themes/default/package.json
  src/themes/default/scripts/rollup.config.js
  src/themes/ecl/bcl-builder.config.js
  src/themes/ecl/icons/bootstrap-icons.svg
  src/themes/ecl/package.json
  src/themes/ecl/scripts/rollup.config.js
  storybook/.storybook/manager-head.html
  storybook/package.json
  yarn.lock
Labels: tag: new feature

#10 feat(drupal-attributes): Refactored multiple components - FRONT-2419
  src/components/accordion/accordion.html.twig
  src/components/accordion/accordion.story.js
  src/components/badge/badge.html.twig
  src/components/badge/badge.story.js
  src/components/badge/badge.test.js
  src/components/dropdown/dropdown.html.twig
  src/components/dropdown/dropdown.story.js
  src/components/dropdown/dropdown.test.js
  src/components/list-group/__snapshots__/list-group.test.js.snap
  src/components/list-group/list-group.html.twig
  src/components/list-group/list-group.story.js
  src/components/navigation/navigation.html.twig
  src/components/offcanvas/offcanvas.html.twig
  src/components/offcanvas/offcanvas.story.js
  src/components/offcanvas/offcanvas.test.js
  src/data/accordion/data.js
  src/data/badge/data.js
  src/data/dropdown/data.js
  src/data/list-group/actionableData.js
  src/data/list-group/data.js
  src/data/list-group/orderedData.js
  src/data/offcanvas/data.js
Labels: tag: new feature

#11 feat(drupal-attributes): Refactored select, input, form with drupal attributes - FRONT-2428
  src/components/form-input/__snapshots__/form-input.test.js.snap
  src/components/form-input/form-input.html.twig
  src/components/form-input/form-input.story.js
  src/components/form-input/form-input.test.js
  src/components/form/__snapshots__/form.test.js.snap
  src/components/form/form.html.twig
  src/components/navbar/__snapshots__/navbar.test.js.snap
  src/components/select/__snapshots__/select.test.js.snap
  src/components/select/select.html.twig
  src/components/select/select.story.js
  src/components/select/select.test.js
  src/data/button-group/inputGroupData.js
  src/data/button-group/toolbarData.js
  src/data/form-input/data.js
  src/data/form/data-disabled.js
  src/data/form/data-grid.js
  src/data/form/data-horizontal.js
  src/data/form/data-inline.js
  src/data/form/data.js
  src/data/list-group/data.js
  src/data/list-group/orderedData.js
  src/data/navbar/data.js
  src/data/select/data.js
  tools/story-utils/index.js
Labels: tag: new feature

#12 feat(drupal-attributes): Refactored breadcrumb, card, card-layout, button-group - FRONT-2430
  src/components/breadcrumb/breadcrumb.html.twig
  src/components/breadcrumb/breadcrumb.test.js
  src/components/button-group/__snapshots__/button-group.test.js.snap
  src/components/button-group/button-group.html.twig
  src/components/button-group/button-group.story.js
  src/components/button-group/button-group.test.js
  src/components/card-layout/__snapshots__/card-layout.test.js.snap
  src/components/card-layout/card-layout.html.twig
  src/components/card-layout/card-layout.story.js
  src/components/card-layout/card-layout.test.js
  src/components/card/__snapshots__/card.test.js.snap
  src/components/card/card.html.twig
  src/components/card/card.story.js
  src/components/card/card.test.js
  src/data/breadcrumb/data.js
  src/data/button-group/data.js
  src/data/button-group/inputGroupData.js
  src/data/button-group/toolbarData.js
  src/data/card-layout/dataGrid.js
  src/data/card-layout/dataGroup.js
  src/data/card-layout/dataMasonry.js
  src/data/card/data.js
  src/data/card/dataHorizontal.js
Labels: process: review needed, tag: new feature

#13 feat(drupal-attributes): Refactored multiple components - FRONT-2434
  src/components/button-group/button-group.html.twig
  src/components/card-layout/card-layout.html.twig
  src/components/card/card.html.twig
  src/components/carousel/__snapshots__/carousel.test.js.snap
  src/components/carousel/carousel.html.twig
  src/components/carousel/carousel.story.js
  src/components/carousel/carousel.test.js
  src/components/form-input/form-input.story.js
  src/components/header/__snapshots__/header.test.js.snap
  src/components/navbar/__snapshots__/navbar.test.js.snap
  src/components/navbar/navbar.html.twig
  src/components/navbar/navbar.story.js
  src/components/navbar/navbar.test.js
  src/components/navigation/navigation.html.twig
  src/components/navigation/navigation.story.js
  src/components/navigation/navigation.test.js
  src/components/pagination/pagination.html.twig
  src/components/progress/progress.html.twig
  src/components/progress/progress.story.js
  src/components/textarea/__snapshots__/textarea.test.js.snap
  src/components/textarea/textarea.html.twig
  src/components/textarea/textarea.story.js
  src/components/textarea/textarea.test.js
  src/components/toasts/toasts.html.twig
  src/data/card-layout/dataGrid.js
  src/data/card-layout/dataGroup.js
  src/data/card-layout/dataMasonry.js
  src/data/carousel/data.js
  src/data/header/data-ecl.js
  src/data/header/data.js
  src/data/navbar/data.js
  src/data/navigation/data.js
  src/data/navigation/dataTabs.js
  src/data/pagination/data.js
  src/data/pagination/dataCustomIcons.js
  src/data/progress/data.js
  src/data/textarea/data.js
  src/data/toasts/data-multiple.js
  src/data/toasts/data.js
Labels: process: review needed, tag: new feature

#15 chore(deps): Updating storybook and some other dep
  builder/package.json
  package.json
  storybook/package.json
  yarn.lock
Labels: tag: internal

#18 fix: Bug fix h-100 remove class on card group story - FRONT-2445
  src/data/card-layout/dataGroup.js
Labels: tag: bug fix

#20 feat(badge): Review badge component twig file. - FRONT-2448
  src/components/bcl-badge/__snapshots__/badge.test.js.snap
  src/components/bcl-badge/badge.html.twig
  src/components/bcl-badge/badge.test.js
Labels: enhancement, process: review needed

#21 feat(drupal-attributes): Adding drupal attributes in templates when they are included using the "only" keyword - FRONT-2462
  src/components/bcl-badge/badge.html.twig
  src/components/bcl-breadcrumb/breadcrumb.html.twig
  src/components/bcl-button/button.html.twig
  src/components/bcl-card-layout/card-layout.html.twig
  src/components/bcl-card/card.html.twig
  src/components/bcl-dropdown/dropdown.html.twig
  src/components/bcl-form-input/form-input.html.twig
  src/components/bcl-icon/icon.html.twig
  src/components/bcl-link/link.html.twig
  src/components/bcl-modal/modal.html.twig
  src/components/bcl-navbar/navbar.html.twig
  src/components/bcl-navigation/navigation.html.twig
  src/components/bcl-select/select.html.twig
  src/components/bcl-spinner/spinner.html.twig
  src/components/bcl-textarea/textarea.html.twig
  src/data/breadcrumb/data.js
  src/data/button-group/data.js
  src/data/button-group/inputGroupData.js
  src/data/button-group/toolbarData.js
  src/data/button/data.js
  src/data/button/spinnerData.js
  src/data/card-layout/dataGroup.js
  src/data/form-input/data.js
  src/data/form/data-disabled.js
  src/data/form/data-grid.js
  src/data/form/data-horizontal.js
  src/data/form/data-inline.js
  src/data/form/data.js
  src/data/header/data-ecl.js
  src/data/header/data.js
  src/data/icon/data.js
  src/data/link/data.js
  src/data/list-group/data.js
  src/data/list-group/orderedData.js
  src/data/modal/data.js
  src/data/navbar/data.js
  src/data/pagination/dataCustomIcons.js
  src/data/select/data.js
  src/data/spinner/data.js
  src/data/textarea/data.js
Labels: tag: bug fix

#22 chore(deps): All the available updates
  builder/package.json
  yarn.lock
Labels: tag: internal

#23 feat(drupal-attributes): Refactored reset of drupal attributes - FRONT-2472
  src/components/bcl-accordion/accordion.story.js
  src/components/bcl-badge/badge.story.js
  src/components/bcl-button-group/button-group.story.js
  src/components/bcl-button/button.story.js
  src/components/bcl-card-layout/card-layout.story.js
  src/components/bcl-card/card.story.js
  src/components/bcl-carousel/carousel.story.js
  src/components/bcl-dropdown/dropdown.story.js
  src/components/bcl-form-input/form-input.story.js
  src/components/bcl-link/link.story.js
  src/components/bcl-list-group/list-group.story.js
  src/components/bcl-modal/modal.story.js
  src/components/bcl-navbar/navbar.story.js
  src/components/bcl-navigation/navigation.story.js
  src/components/bcl-offcanvas/offcanvas.story.js
  src/components/bcl-select/select.story.js
  src/components/bcl-table/table.html.twig
  src/components/bcl-table/table.story.js
  src/components/bcl-textarea/textarea.story.js
Labels: tag: new feature

#26 feat(image structure): Added parse image in carousel for drupal structure of images - FRONT-2591
  src/components/bcl-carousel/carousel.html.twig
  src/components/bcl-carousel/carousel.story.js
  src/components/bcl-carousel/carousel.test.js
Labels: tag: new feature

#2 feat(multiselect): Added multiselect - FRONT-2351
  package.json
  src/components/bcl-select/__snapshots__/select.test.js.snap
  src/components/bcl-select/select.html.twig
  src/components/bcl-select/select.story.js
  src/components/bcl-select/select.test.js
  src/data/select/dataMultiselect.js
  src/themes/default/bcl-builder.config.js
  src/themes/default/oe-bcl-default.scss
  src/themes/default/package.json
  src/themes/default/scss/_multiselect.scss
  storybook/.storybook/preview-head.html
  tools/story-utils/index.js
  yarn.lock
Labels: tag: new feature

#27 FRONT-2598: Fix Drupal non-numeric value issue.
  src/components/bcl-button/button.html.twig
Labels: bug, process: review needed

#3 feat(search): Added search page - FRONT-2348
  package.json
  src/components/bcl-badge/badge.html.twig
  src/components/bcl-badge/badge.story.js
  src/components/bcl-card/card.html.twig
  src/components/bcl-form-input/form-input.html.twig
  src/components/bcl-pagination/pagination.html.twig
  src/compositions/bcl-search/dataSearch.js
  src/compositions/bcl-search/search.html.twig
  src/compositions/bcl-search/search.story.js
  src/themes/default/scss/_icon.scss
  storybook/.storybook/main.js
  storybook/.storybook/preview-head.html
Labels: process: review needed, question, tag: new feature

#29 bug(offcanvas-search): Fixed bug on search page offcanvas - FRONT-2604
  storybook/.storybook/preview-head.html
Labels: bug

#25 chore(storybook): Refactoring select controls options, removing argType.defaultValue
  src/components/bcl-accordion/accordion.story.js
  src/components/bcl-alert/alert.story.js
  src/components/bcl-badge/badge.story.js
  src/components/bcl-blockquote/blockquote.story.js
  src/components/bcl-breadcrumb/breadcrumb.story.js
  src/components/bcl-button-group/button-group.story.js
  src/components/bcl-button/button.story.js
  src/components/bcl-card-layout/card-layout.story.js
  src/components/bcl-card/card.story.js
  src/components/bcl-carousel/carousel.story.js
  src/components/bcl-dropdown/dropdown.story.js
  src/components/bcl-form-input/form-input.story.js
  src/components/bcl-icon/icon.story.js
  src/components/bcl-link/link.story.js
  src/components/bcl-list-group/list-group.story.js
  src/components/bcl-modal/modal.story.js
  src/components/bcl-navbar/navbar.story.js
  src/components/bcl-navigation/navigation.story.js
  src/components/bcl-offcanvas/offcanvas.story.js
  src/components/bcl-pagination/pagination.story.js
  src/components/bcl-progress/progress.story.js
  src/components/bcl-select/__snapshots__/select.test.js.snap
  src/components/bcl-select/select.story.js
  src/components/bcl-spinner/spinner.story.js
  src/components/bcl-table/table.story.js
  src/components/bcl-textarea/textarea.story.js
  src/components/bcl-toasts/toasts.story.js
  src/data/pagination/data.js
  src/data/select/data.js
  tools/story-utils/index.js
Labels: tag: internal

#31 feat(modal): Add missing bootstrap params - FRONT-2686
  src/components/bcl-header/__snapshots__/header.test.js.snap
  src/components/bcl-modal/__snapshots__/modal.test.js.snap
  src/components/bcl-modal/modal.html.twig
  src/components/bcl-modal/modal.story.js
  src/components/bcl-modal/modal.test.js
Labels: tag: enhancement

#24 feat(refactor-progress): Added refactor of progress bar - FRONT-2494
  src/components/bcl-progress/__snapshots__/progress.test.js.snap
  src/components/bcl-progress/progress.html.twig
  src/components/bcl-progress/progress.story.js
  src/components/bcl-progress/progress.test.js
  src/data/progress/data.js
Labels: tag: new feature

#33 chore(deps): updates - 30/07/21
  builder/package.json
  package.json
  storybook/package.json
  yarn.lock
Labels: tag: internal
