Repository openeuropa/bootstrap-component-library, pull requests merged in 2021-11, with the labels that each got.

#118 chore(deps): updates 03-11-21
  bootstrap/package.json
  builder/package.json
  package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal

#115 feat(builder): Adding rename script - FRONT-3338
  README.md
  builder/bin/build.js
  builder/scripts/rename.js
  docs/packages.md
Labels: tag: enhancement

#112 feat(ucpkn-variables): Added ucpkn variables. - FRONT-3330
  src/themes/ucpkn/src/scss/base/_variables.scss
  src/themes/ucpkn/src/scss/oe-bcl-ucpkn.scss
Labels: tag: new feature

#120 fix(card): Fixing bug in title attributes - front-3349
  src/components/bcl-card/__snapshots__/card.test.js.snap
  src/components/bcl-card/card.html.twig
  src/components/bcl-card/card.test.js
Labels: tag: bug fix, process: review needed

#119 fix(toast): Fixing issue with the autoescape - FRONT-3353
  src/components/bcl-toasts/toasts.html.twig
Labels: tag: bug fix, process: review needed

#123 feat(links): Added Underline hover class on link - FRONT-3334
  src/components/bcl-link/__snapshots__/link.test.js.snap
  src/components/bcl-link/link.html.twig
  src/components/bcl-link/link.story.js
  src/components/bcl-link/link.test.js
  src/compositions/bcl-footer/__snapshots__/footer.test.js.snap
  src/compositions/bcl-footer/footer.html.twig
  src/compositions/bcl-group-landing-listing/__snapshots__/group-landing-listing.test.js.snap
  src/compositions/bcl-group-landing-listing/dataList.js
  src/compositions/bcl-group-landing-listing/dataListContent.js
  src/compositions/bcl-group-landing-listing/dataListMember.js
  src/compositions/bcl-group-landing/__snapshots__/group-landing.test.js.snap
  src/compositions/bcl-group-landing/data.js
  src/compositions/bcl-listing/__snapshots__/listing.test.js.snap
  src/compositions/bcl-listing/data/listing--default-1-col.js
  src/compositions/bcl-listing/data/listing--default-2-col.js
  src/compositions/bcl-listing/data/listing--default-3-col.js
  src/compositions/bcl-listing/data/listing--highlight-1-col.js
  src/compositions/bcl-listing/data/listing--highlight-2-col.js
  src/compositions/bcl-listing/data/listing--highlight-3-col.js
  src/compositions/bcl-recent-activities/__snapshots__/recent-activities.test.js.snap
  src/compositions/bcl-recent-activities/data.js
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-search/dataSearch.js
  src/compositions/bcl-user-view/__snapshots__/user-view.test.js.snap
  src/compositions/bcl-user-view/user-view-compact.html.twig
  src/data/footer/data.js
  src/themes/default/src/scss/_utilities.scss
Labels: tag: new feature

#116 feat(compositions): Adding Fact & Figures composition - FRONT-3256
  src/components/bcl-twig-templates/package.json
  src/compositions/bcl-fact-figures/.npmignore
  src/compositions/bcl-fact-figures/__snapshots__/fact-figures.test.js.snap
  src/compositions/bcl-fact-figures/data/data.js
  src/compositions/bcl-fact-figures/fact-figures.html.twig
  src/compositions/bcl-fact-figures/fact-figures.story.js
  src/compositions/bcl-fact-figures/fact-figures.test.js
  src/compositions/bcl-fact-figures/package.json
Labels: tag: new feature

#126 feat(utilities): Add bg-lighter utility. - FRONT-3363
  src/compositions/bcl-banner/__snapshots__/banner.test.js.snap
  src/compositions/bcl-banner/dataDefault.js
  src/compositions/bcl-banner/dataImage.js
  src/compositions/bcl-banner/dataShade.js
  src/compositions/bcl-featured-media/__snapshots__/featured-media.test.js.snap
  src/compositions/bcl-featured-media/data.js
  src/compositions/bcl-featured-media/dataImage.js
  src/compositions/bcl-featured-media/dataVideo.js
  src/compositions/bcl-group-landing-listing/__snapshots__/group-landing-listing.test.js.snap
  src/compositions/bcl-group-landing-listing/group-landing-listing.html.twig
  src/compositions/bcl-group-landing/__snapshots__/group-landing.test.js.snap
  src/compositions/bcl-group-landing/group-landing.html.twig
  src/compositions/bcl-listing/__snapshots__/listing.test.js.snap
  src/compositions/bcl-listing/listing.html.twig
  src/compositions/bcl-recent-activities/__snapshots__/recent-activities.test.js.snap
  src/compositions/bcl-recent-activities/recent-activities.html.twig
  src/themes/default/src/scss/_utilities.scss
  src/themes/default/src/scss/_variables.scss
Labels: tag: enhancement

#127 feat(npmignore): Added npmignore to all compositions - FRONT-3365
  src/compositions/bcl-banner/.npmignore
  src/compositions/bcl-featured-media/.npmignore
  src/compositions/bcl-group-landing-listing/.npmignore
  src/compositions/bcl-group-landing/.npmignore
  src/compositions/bcl-links-block/.npmignore
  src/compositions/bcl-listing/.npmignore
  src/compositions/bcl-recent-activities/.npmignore
  src/compositions/bcl-search-form/.npmignore
  src/compositions/bcl-search/.npmignore
  src/compositions/bcl-user-edit/.npmignore
  src/compositions/bcl-user-listing/.npmignore
  src/compositions/bcl-user-view/.npmignore
Labels: tag: internal

#117 feat(compositions): Add Timeline composition - FRONT-2571
  src/components/bcl-twig-templates/package.json
  src/compositions/bcl-timeline/.npmignore
  src/compositions/bcl-timeline/__snapshots__/timeline.test.js.snap
  src/compositions/bcl-timeline/dataDefault.js
  src/compositions/bcl-timeline/package.json
  src/compositions/bcl-timeline/timeline.html.twig
  src/compositions/bcl-timeline/timeline.story.js
  src/compositions/bcl-timeline/timeline.test.js
  src/themes/default/src/scss/_timeline.scss
  src/themes/default/src/scss/oe-bcl-default.scss
  src/themes/joinup/src/scss/oe-bcl-joinup.scss
  src/themes/ucpkn/src/scss/oe-bcl-ucpkn.scss
Labels: tag: new feature

#129 fix(badge): Fix badge icon misalignment on Safari and IE - FRONT-3374
  src/themes/default/src/scss/_badge.scss
Labels: tag: bug fix

#125 feat(listing): Listing on all compositions - FRONT-3357
  src/compositions/bcl-group-landing-listing/__snapshots__/group-landing-listing.test.js.snap
  src/compositions/bcl-group-landing-listing/dataList.js
  src/compositions/bcl-group-landing-listing/dataListContent.js
  src/compositions/bcl-group-landing-listing/dataListMember.js
  src/compositions/bcl-group-landing-listing/group-landing-listing.html.twig
  src/compositions/bcl-group-landing-listing/package.json
  src/compositions/bcl-group-landing/__snapshots__/group-landing.test.js.snap
  src/compositions/bcl-landing-page/__snapshots__/landing-page.test.js.snap
  src/compositions/bcl-listing/__snapshots__/listing.test.js.snap
  src/compositions/bcl-listing/listing.html.twig
  src/compositions/bcl-listing/listing.test.js
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-search/dataSearch.js
  src/compositions/bcl-search/search.html.twig
  src/compositions/bcl-user-listing/__snapshots__/user-listing.test.js.snap
  src/compositions/bcl-user-listing/data-user-listing.js
  src/compositions/bcl-user-listing/user-listing.html.twig
  src/compositions/bcl-user-listing/user-listing.story.js
Labels: tag: enhancement

#134 feat(ucpkn): Changed variables - FRONT-3372
  src/themes/ucpkn/logo/ucpkn_logo.svg
  src/themes/ucpkn/src/scss/base/_variables.scss
Labels: tag: enhancement

#133 feat(description-list): Added description list - FRONT-2562
  src/components/bcl-twig-templates/package.json
  src/compositions/bcl-description-list/__snapshots__/description-list.test.js.snap
  src/compositions/bcl-description-list/data.js
  src/compositions/bcl-description-list/dataHorizontal.js
  src/compositions/bcl-description-list/description-list.html.twig
  src/compositions/bcl-description-list/description-list.story.js
  src/compositions/bcl-description-list/description-list.test.js
  src/compositions/bcl-description-list/package.json
  src/themes/default/src/scss/_utilities.scss
Labels: tag: new feature

#132 feat(file): Added file paragraph. - Front 3139
  src/components/bcl-twig-templates/package.json
  src/compositions/bcl-file/.npmignore
  src/compositions/bcl-file/__snapshots__/file.test.js.snap
  src/compositions/bcl-file/data.js
  src/compositions/bcl-file/dataCard.js
  src/compositions/bcl-file/file.html.twig
  src/compositions/bcl-file/file.story.js
  src/compositions/bcl-file/file.test.js
  src/compositions/bcl-file/package.json
Labels: tag: new feature

#136 fix(card): Fix title attributes and duplicated image in card component - FRONT-3398
  src/components/bcl-card-layout/__snapshots__/card-layout.test.js.snap
  src/components/bcl-card/__snapshots__/card.test.js.snap
  src/components/bcl-card/card.html.twig
  src/components/bcl-card/card.test.js
  src/compositions/bcl-group-landing-listing/__snapshots__/group-landing-listing.test.js.snap
  src/compositions/bcl-group-landing-listing/dataList.js
  src/compositions/bcl-group-landing-listing/dataListContent.js
  src/compositions/bcl-group-landing-listing/dataListMember.js
  src/compositions/bcl-listing/__snapshots__/listing.test.js.snap
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-search/dataSearch.js
  src/compositions/bcl-user-listing/__snapshots__/user-listing.test.js.snap
  src/compositions/bcl-user-listing/data-user-listing.js
  src/compositions/bcl-user-view/__snapshots__/user-view.test.js.snap
  src/compositions/bcl-user-view/dataUserView.js
Labels: tag: new feature, process: review needed

#135 feat(news): Adding News screens - FRONT-3395
  src/components/bcl-twig-templates/package.json
  src/compositions/bcl-base-templates/content-type.html.twig
  src/compositions/bcl-base-templates/listing-page.html.twig
  src/compositions/bcl-base-templates/package.json
  src/compositions/bcl-base-templates/sidebar-search.html.twig
  src/compositions/bcl-content-banner/.npmignore
  src/compositions/bcl-content-banner/__snapshots__/content-banner.test.js.snap
  src/compositions/bcl-content-banner/content-banner.html.twig
  src/compositions/bcl-content-banner/content-banner.story.js
  src/compositions/bcl-content-banner/content-banner.test.js
  src/compositions/bcl-content-banner/data/data.js
  src/compositions/bcl-content-banner/package.json
  src/compositions/bcl-news/.npmignore
  src/compositions/bcl-news/__snapshots__/bcl-news.test.js.snap
  src/compositions/bcl-news/bcl-news.story.js
  src/compositions/bcl-news/bcl-news.test.js
  src/compositions/bcl-news/data/data_content.js
  src/compositions/bcl-news/data/data_listing.js
  src/compositions/bcl-news/package.json
  src/data/footer/data.js
  src/data/header/data--simple.js
  src/themes/default/src/scss/_banners.scss
  src/themes/default/src/scss/_utilities.scss
  yarn.lock
Labels: process: on hold, tag: new feature, process: review needed

#141 docs(fact-figures): Add missing documentation - FRONT-3417
  src/compositions/bcl-fact-figures/fact-figures.html.twig
Labels: tag: documentation

#144 fix(joinup): Use default line-height for headings. - FRONT-3426
  src/themes/joinup/src/scss/base/_variables.scss
Labels: process: review needed

#145 chore: Adding decorators as story utilities
  src/components/bcl-badge/badge.story.js
  src/components/bcl-button/button.story.js
  src/components/bcl-link/link.story.js
  src/components/bcl-scrollspy/scrollspy.story.js
  src/compositions/bcl-group-landing-listing/group-landing-listing.story.js
  src/compositions/bcl-inpage-navigation/inpage-navigation.story.js
  src/compositions/bcl-landing-page/landing-page.story.js
  src/compositions/bcl-links-block/links-block.story.js
  src/compositions/bcl-listing/listing.story.js
  src/compositions/bcl-news/bcl-news.story.js
  src/compositions/bcl-page/bcl-page.story.js
  src/compositions/bcl-search-form/search-form.story.js
  src/compositions/bcl-search/search.story.js
  tools/story-utils/index.js
Labels: tag: internal, process: review needed

#142 feat(paragraphs): Homogenize titles across all Paragraphs. - FRONT-3418
  src/compositions/bcl-banner/__snapshots__/banner.test.js.snap
  src/compositions/bcl-banner/banner.html.twig
  src/compositions/bcl-banner/banner.story.js
  src/compositions/bcl-banner/banner.test.js
  src/compositions/bcl-description-list/__snapshots__/description-list.test.js.snap
  src/compositions/bcl-description-list/description-list.html.twig
  src/compositions/bcl-description-list/description-list.story.js
  src/compositions/bcl-description-list/description-list.test.js
  src/compositions/bcl-fact-figures/__snapshots__/fact-figures.test.js.snap
  src/compositions/bcl-fact-figures/fact-figures.html.twig
  src/compositions/bcl-fact-figures/fact-figures.story.js
  src/compositions/bcl-fact-figures/fact-figures.test.js
  src/compositions/bcl-featured-media/__snapshots__/featured-media.test.js.snap
  src/compositions/bcl-featured-media/featured-media.html.twig
  src/compositions/bcl-featured-media/featured-media.story.js
  src/compositions/bcl-featured-media/featured-media.test.js
  src/compositions/bcl-file/__snapshots__/file.test.js.snap
  src/compositions/bcl-file/data.js
  src/compositions/bcl-file/dataCard.js
  src/compositions/bcl-file/file.html.twig
  src/compositions/bcl-file/file.test.js
  src/compositions/bcl-landing-page/__snapshots__/landing-page.test.js.snap
  src/compositions/bcl-links-block/__snapshots__/links-block.test.js.snap
  src/compositions/bcl-links-block/links-block.html.twig
  src/compositions/bcl-links-block/links-block.story.js
  src/compositions/bcl-links-block/links-block.test.js
  src/compositions/bcl-listing/__snapshots__/listing.test.js.snap
  src/compositions/bcl-listing/listing.html.twig
  src/compositions/bcl-listing/listing.story.js
  src/compositions/bcl-listing/listing.test.js
  src/compositions/bcl-timeline/__snapshots__/timeline.test.js.snap
  src/compositions/bcl-timeline/timeline.html.twig
  src/compositions/bcl-timeline/timeline.story.js
  src/compositions/bcl-timeline/timeline.test.js
Labels: tag: breaking change, process: review needed

#148 fix(header): Added header fix - FRONT-3419
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-header/header.html.twig
  src/compositions/bcl-landing-page/__snapshots__/landing-page.test.js.snap
  src/compositions/bcl-page/__snapshots__/bcl-page.test.js.snap
  src/themes/default/src/scss/_header.scss
Labels: tag: bug fix
