Repository openeuropa/bootstrap-component-library, pull requests merged in 2021-08, with the labels that each got.

#34 feat(param): Renamed type to input_type in form_input - FRONT-2687
  src/components/bcl-form-input/form-input.html.twig
  src/components/bcl-form-input/form-input.story.js
  src/components/bcl-form-input/form-input.test.js
  src/compositions/bcl-search/dataSearch.js
  src/data/button-group/inputGroupData.js
  src/data/button-group/toolbarData.js
  src/data/form/data-disabled.js
  src/data/form/data-grid.js
  src/data/form/data-horizontal.js
  src/data/form/data-inline.js
  src/data/form/data.js
  src/data/list-group/data.js
  src/data/list-group/orderedData.js
Labels: tag: breaking change, process: review needed

#39 feat(offcanvas): Added offcanvas improvements - FRONT-2699
  .storybook/environment.js
  .storybook/preview-head.html
  src/components/bcl-offcanvas/offcanvas.html.twig
  src/components/bcl-twig-templates/package.json
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-search/dataSearch.js
  src/compositions/bcl-search/search-offcanvas.html.twig
  src/compositions/bcl-search/search.html.twig
  src/compositions/bcl-search/search.story.js
  src/compositions/bcl-search/search.test.js
  src/themes/default/storybook/.storybook/preview-head.html
  src/themes/ecl/storybook/.storybook/preview-head.html
  src/themes/joinup/storybook/.storybook/preview-head.html
Labels: tag: enhancement

#47 chore(deps): Updates 17-08-21
  bootstrap/package.json
  builder/package.json
  package.json
  src/themes/default/src/js/index.esm.js
  src/themes/default/src/js/index.umd.js
  src/themes/default/storybook/package.json
  src/themes/ecl/src/js/index.esm.js
  src/themes/ecl/src/js/index.umd.js
  src/themes/ecl/storybook/package.json
  src/themes/joinup/src/js/index.esm.js
  src/themes/joinup/src/js/index.umd.js
  src/themes/joinup/storybook/package.json
  yarn.lock
Labels: tag: internal

#45 feat(search-improvements): Improvements on search - FRONT-2785
  .storybook/preview-head.html
  src/components/bcl-badge/badge.story.js
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-search/dataSearch.js
  src/compositions/bcl-search/search.html.twig
  src/compositions/bcl-search/search.story.js
  src/themes/default/src/scss/_bcl-offcanvas.scss
  src/themes/default/src/scss/oe-bcl-default.scss
  src/themes/default/storybook/.storybook/preview-head.html
  src/themes/ecl/src/scss/oe-bcl-ecl.scss
  src/themes/ecl/storybook/.storybook/preview-head.html
  src/themes/joinup/src/scss/oe-bcl-joinup.scss
  src/themes/joinup/storybook/.storybook/preview-head.html
Labels: tag: enhancement

#40 feat(multiselect): Restyling of multiselect - FRONT-2592
  src/components/bcl-select/__snapshots__/select.test.js.snap
  src/components/bcl-select/select.story.js
  src/data/select/dataMultiselect.js
  src/themes/default/src/scss/_multiselect.scss
  tools/story-utils/index.js
Labels: tag: enhancement

#46 feat(form-validation): Adding validation parameters to the form-input fields and demo improvement on forms - FRONT-2808
  src/components/bcl-form-input/__snapshots__/form-input.test.js.snap
  src/components/bcl-form-input/form-input.html.twig
  src/components/bcl-form-input/form-input.story.js
  src/components/bcl-form-input/form-input.test.js
  src/components/bcl-form/__snapshots__/form.test.js.snap
  src/components/bcl-form/form.html.twig
  src/components/bcl-form/form.story.js
  src/components/bcl-select/__snapshots__/select.test.js.snap
  src/components/bcl-select/select.html.twig
  src/components/bcl-select/select.story.js
  src/components/bcl-select/select.test.js
  src/components/bcl-textarea/__snapshots__/textarea.test.js.snap
  src/components/bcl-textarea/textarea.html.twig
  src/components/bcl-textarea/textarea.story.js
  src/components/bcl-textarea/textarea.test.js
  src/data/form-input/data.js
  src/data/form/data-disabled.js
  src/data/form/data-grid.js
  src/data/form/data-horizontal.js
  src/data/form/data-inline.js
  src/data/form/data.js
  src/data/select/data.js
  src/data/select/dataMultiselect.js
  src/data/textarea/data.js
  src/themes/default/src/scss/_multiselect.scss
  tools/story-utils/index.js
Labels: tag: enhancement

#50 chore(deps): Updates 30-08-21
  builder/package.json
  package.json
  src/themes/default/storybook/package.json
  src/themes/ecl/storybook/package.json
  src/themes/joinup/storybook/package.json
  yarn.lock
Labels: tag: internal
