Repository openeuropa/bootstrap-component-library, pull requests merged in 2021-12, with the labels that each got.

#154 feat(flags): Adding flag example in icon, distributing sprite with the themes - FRONT-3430
  .gitignore
  src/components/bcl-icon/__snapshots__/icon.test.js.snap
  src/components/bcl-icon/icon.story.js
  src/data/icon/data.js
  src/data/icon/package.json
  src/themes/default/bcl-builder.config.js
  src/themes/default/package.json
  src/themes/joinup/bcl-builder.config.js
  src/themes/joinup/package.json
  src/themes/ucpkn/bcl-builder.config.js
  src/themes/ucpkn/package.json
  tools/story-utils/index.js
  yarn.lock
Labels: process: change requested, tag: new feature

#151 fix(listing): Fixing alignment classes - FRONT-3405
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-listing/__snapshots__/listing.test.js.snap
  src/compositions/bcl-listing/listing.html.twig
  src/compositions/bcl-listing/listing.story.js
  src/compositions/bcl-listing/listing.test.js
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
Labels: tag: bug fix

#158 chore(deps): green updates
  bootstrap/package.json
  builder/package.json
  package.json
  src/components/bcl-scrollspy/navScrollspy.html
  src/data/icon/package.json
  src/themes/default/package.json
  src/themes/default/src/scss/_multiselect.scss
  src/themes/default/storybook/package.json
  src/themes/joinup/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/package.json
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal

#156 feat(icon-list): Updated list of icons - FRONT-3437
  bootstrap/bootstrap-icons.js
Labels: tag: enhancement

#152 feat(badges): Added outline "variant" - FRONT-3429
  src/components/bcl-badge/__snapshots__/badge.test.js.snap
  src/components/bcl-badge/badge.html.twig
  src/components/bcl-badge/badge.story.js
  src/components/bcl-badge/badge.test.js
  src/components/bcl-card/__snapshots__/card.test.js.snap
  src/components/bcl-card/card.html.twig
  src/components/bcl-card/card.story.js
  src/components/bcl-list-group/__snapshots__/list-group.test.js.snap
  src/compositions/bcl-content-banner/__snapshots__/content-banner.test.js.snap
  src/compositions/bcl-content-banner/data/data.js
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-event/data/event-sidebar.js
  src/compositions/bcl-file/__snapshots__/file.test.js.snap
  src/compositions/bcl-file/dataCard.js
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-group/dataLanding.js
  src/compositions/bcl-group/dataList.js
  src/compositions/bcl-group/dataListContent.js
  src/compositions/bcl-listing/__snapshots__/listing.test.js.snap
  src/compositions/bcl-listing/data/listing--date.js
  src/compositions/bcl-listing/listing.html.twig
  src/compositions/bcl-news/__snapshots__/bcl-news.test.js.snap
  src/compositions/bcl-news/data/data_listing.js
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-search/dataSearch.js
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/compositions/bcl-user/data-user-edit.js
  src/compositions/bcl-user/data-user-listing.js
  src/compositions/bcl-user/data-user-view.js
  src/compositions/bcl-user/user.story.js
  src/data/card/data.js
  src/themes/default/src/scss/_badge.scss
Labels: tag: new feature

#155 enhancement(sort): Redone duplicate sort listing - OEL-727
  src/compositions/bcl-base-templates/listing-page.html.twig
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-group/data.js
  src/compositions/bcl-news/__snapshots__/bcl-news.test.js.snap
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/compositions/bcl-user/data-user-listing.js
Labels: process: under review, tag: enhancement

#161 fix(inpage-navigation): Changing selector used for styling - OEL-839
  src/components/bcl-scrollspy/groupScrollspy.html
  src/components/bcl-scrollspy/navScrollspy.html
  src/compositions/bcl-inpage-navigation/__snapshots__/inpage-navigation.test.js.snap
  src/compositions/bcl-inpage-navigation/inpage-navigation.html.twig
  src/compositions/bcl-page/__snapshots__/bcl-page.test.js.snap
  src/themes/default/src/scss/_inpage-navigation.scss
Labels: tag: bug fix, process: review needed

#159 feat(navigation): Added support for multiple levels - OEL-834
  src/components/bcl-navigation/navigation.html.twig
  src/components/bcl-navigation/navigation.test.js
  src/components/bcl-scrollspy/listScrollspy.html
  src/components/bcl-scrollspy/scrollspy.story.js
  src/compositions/bcl-inpage-navigation/__snapshots__/inpage-navigation.test.js.snap
  src/compositions/bcl-inpage-navigation/dataDefault.js
  src/data/navigation/dataMultiple.js
Labels: tag: enhancement

#164 fix(breadcrumb): fixing segment attributes - FRONT-840
  src/components/bcl-breadcrumb/breadcrumb.html.twig
Labels: tag: bug fix, process: review needed

#165 enhancement(listing): Fix for listing when image is not available - OEL-841
  src/compositions/bcl-listing/__snapshots__/listing.test.js.snap
  src/compositions/bcl-listing/listing.html.twig
Labels: tag: enhancement

#166 style(accordion): Accordion active state - OEL-844
  src/themes/default/src/scss/_variables.scss
Labels: tag: enhancement

#162 feat(layout): Adaptive layout approach - OEL-828
  src/compositions/bcl-base-templates/content-type.html.twig
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-group/dataLanding.js
  src/compositions/bcl-group/group.html.twig
  src/compositions/bcl-landing-page/__snapshots__/landing-page.test.js.snap
  src/compositions/bcl-landing-page/data.js
  src/compositions/bcl-news/__snapshots__/bcl-news.test.js.snap
  src/compositions/bcl-page/__snapshots__/bcl-page.test.js.snap
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/compositions/bcl-user/data-user-edit.js
  src/compositions/bcl-user/data-user-listing.js
  src/compositions/bcl-user/data-user-view.js
  src/themes/default/src/scss/_bcl-offcanvas.scss
Labels: tag: enhancement, process: review needed

#167 chore(storybook): Using storybook 6.4.8
  .storybook/main.js
  package.json
  src/components/bcl-badge/badge.story.js
  src/components/bcl-card/card.story.js
  src/components/bcl-dropdown/dropdown.story.js
  src/components/bcl-list-group/list-group.story.js
  src/components/bcl-modal/modal.story.js
  src/components/bcl-navigation/navigation.story.js
  src/components/bcl-pagination/pagination.story.js
  src/components/bcl-progress/progress.story.js
  src/compositions/bcl-banner/banner.story.js
  src/compositions/bcl-date-block/date-block.story.js
  src/compositions/bcl-fact-figures/fact-figures.story.js
  src/compositions/bcl-featured-media/featured-media.story.js
  src/compositions/bcl-links-block/__snapshots__/links-block.test.js.snap
  src/compositions/bcl-links-block/links-block.html.twig
  src/compositions/bcl-links-block/links-block.story.js
  src/compositions/bcl-listing/listing.story.js
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-news/news.story.js
  src/compositions/bcl-news/news.test.js
  src/compositions/bcl-page/__snapshots__/page.test.js.snap
  src/compositions/bcl-page/page.story.js
  src/compositions/bcl-page/page.test.js
  src/compositions/bcl-timeline/timeline.story.js
  src/data/list-group/actionableData.js
  src/data/list-group/orderedData.js
  src/themes/default/storybook/.storybook/main.js
  src/themes/default/storybook/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/package.json
  tools/story-utils/index.js
  yarn.lock
Labels: tag: internal

#169 chore(deps): Audit fix and updates
  package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal

#170 feat(multiselect): Supporting multiple multiselects in our demos - OEL-724
  tools/story-utils/index.js
Labels: tag: internal

#171 feat(placeholder): Adding component - OEL-849
  .size-limit.json
  src/components/bcl-accordion/accordion.html.twig
  src/components/bcl-accordion/accordion.story.js
  src/components/bcl-alert/alert.story.js
  src/components/bcl-badge/badge.story.js
  src/components/bcl-blockquote/blockquote.story.js
  src/components/bcl-breadcrumb/breadcrumb.story.js
  src/components/bcl-button-group/button-group.story.js
  src/components/bcl-button/button.story.js
  src/components/bcl-button/button.test.js
  src/components/bcl-card-layout/card-layout.story.js
  src/components/bcl-card/card.story.js
  src/components/bcl-carousel/carousel.story.js
  src/components/bcl-dropdown/dropdown.story.js
  src/components/bcl-form-input/form-input.story.js
  src/components/bcl-form/form.story.js
  src/components/bcl-icon/icon.story.js
  src/components/bcl-link/link.story.js
  src/components/bcl-list-group/list-group.story.js
  src/components/bcl-modal/modal.story.js
  src/components/bcl-navbar/navbar.story.js
  src/components/bcl-navigation/navigation.story.js
  src/components/bcl-offcanvas/offcanvas.story.js
  src/components/bcl-pagination/pagination.story.js
  src/components/bcl-placeholder/.npmignore
  src/components/bcl-placeholder/__snapshots__/placeholder.test.js.snap
  src/components/bcl-placeholder/package.json
  src/components/bcl-placeholder/placeholder.html.twig
  src/components/bcl-placeholder/placeholder.story.js
  src/components/bcl-placeholder/placeholder.test.js
  src/components/bcl-progress/progress.story.js
  src/components/bcl-scrollspy/scrollspy.story.js
  src/components/bcl-select/select.story.js
  src/components/bcl-spinner/spinner.story.js
  src/components/bcl-table/table.story.js
  src/components/bcl-toasts/toasts.story.js
  src/components/bcl-twig-templates/package.json
  src/compositions/bcl-inpage-navigation/inpage-navigation.story.js
  src/data/placeholder/data.js
  src/data/placeholder/package.json
  src/themes/default/src/scss/oe-bcl-default.scss
  src/themes/joinup/src/scss/oe-bcl-joinup.scss
  src/themes/ucpkn/src/scss/oe-bcl-ucpkn.scss
Labels: tag: new feature, tag: enhancement

#174 chore(storybook): Fixing sub theme start script
  package.json
Labels: tag: internal

#173 chore(builder): Adding svg sprite command
  README.md
  builder/README.md
  builder/bin/build.js
  builder/conf/svgoDefaultPlugins.js
  builder/package.json
  builder/scripts/copy.js
  builder/scripts/scripts.js
  builder/scripts/sprite.js
  builder/scripts/styles.js
  package.json
  yarn.lock
Labels: tag: internal

#176 chore(joinup): Distributing roboto font files
  .gitignore
  package.json
  src/themes/joinup/package.json
  src/themes/joinup/src/scss/base/_fonts.scss
  yarn.lock
Labels: tag: new feature

#177 fix(ucpkn-variables): Added fix for variables and fix for crashing stories - OEL-893
  src/components/bcl-blockquote/blockquote.story.js
  src/components/bcl-card-layout/card-layout.story.js
  src/components/bcl-table/table.story.js
  src/compositions/bcl-content-banner/content-banner.story.js
  src/compositions/bcl-fact-figures/fact-figures.story.js
  src/compositions/bcl-search-form/search-form.story.js
  src/themes/ucpkn/src/scss/base/_variables.scss
Labels: enhancement

#178 chore(deps): Updates, 15-12-21
  bootstrap/bin/build-plugins.js
  bootstrap/package.json
  builder/package.json
  package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal

#179 feat(title): Changed paragraph titles from h4 to h2 - OEL-860
  src/compositions/bcl-description-list/description-list.html.twig
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-fact-figures/__snapshots__/fact-figures.test.js.snap
  src/compositions/bcl-fact-figures/fact-figures.html.twig
  src/compositions/bcl-fact-figures/fact-figures.story.js
  src/compositions/bcl-featured-media/__snapshots__/featured-media.test.js.snap
  src/compositions/bcl-featured-media/featured-media.html.twig
  src/compositions/bcl-featured-media/featured-media.story.js
  src/compositions/bcl-file/file.html.twig
  src/compositions/bcl-links-block/__snapshots__/links-block.test.js.snap
  src/compositions/bcl-links-block/links-block.html.twig
  src/compositions/bcl-links-block/links-block.story.js
  src/compositions/bcl-listing/__snapshots__/listing.test.js.snap
  src/compositions/bcl-listing/listing.html.twig
  src/compositions/bcl-listing/listing.story.js
  src/compositions/bcl-timeline/timeline.html.twig
  src/compositions/bcl-timeline/timeline.story.js
Labels: tag: new feature, process: review needed

#180 feat(card): Added margin bottom on card badges - OEL-880
  src/components/bcl-card/__snapshots__/card.test.js.snap
  src/components/bcl-card/card.html.twig
  src/compositions/bcl-content-banner/__snapshots__/content-banner.test.js.snap
  src/compositions/bcl-file/__snapshots__/file.test.js.snap
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-listing/__snapshots__/listing.test.js.snap
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
Labels: tag: enhancement, process: review needed

#182 feat(ucpkn-header): Fix for overlapping site name - OEL-889
  src/compositions/bcl-header/__snapshots__/header.test.js.snap
  src/data/header/data-ucpkn.js
  src/themes/default/src/scss/_header.scss
  src/themes/ucpkn/src/stories/header.story.js
Labels: tag: enhancement

#181 feat(dropdown-header): Fix for long dropdown items inside header - OEL-891
  src/compositions/bcl-header/__snapshots__/header.test.js.snap
  src/data/header/data-ec.js
  src/themes/default/src/scss/_header.scss
Labels: question, tag: enhancement

#184 chore: Fix wrong library title - OEL-916
  src/compositions/bcl-timeline/__snapshots__/timeline.test.js.snap
  src/compositions/bcl-timeline/dataDefault.js
  static/index.html
Labels: tag: internal

#183 fix(featured-media): Fix media caption size with different image size - OEL-910
  src/compositions/bcl-featured-media/__snapshots__/featured-media.test.js.snap
  src/compositions/bcl-featured-media/dataImage.js
Labels: tag: bug fix, process: review needed

#186 feat(accessibility): Accordion fixes - OEL-917
  src/components/bcl-accordion/__snapshots__/accordion.test.js.snap
  src/components/bcl-accordion/accordion.html.twig
Labels: tag: enhancement

#188 feat(accessibility): List group report - OEL-920
  src/components/bcl-list-group/__snapshots__/list-group.test.js.snap
  src/data/list-group/orderedData.js
Labels: tag: enhancement, process: review needed

#187 feat(accessibility): Select & Multiselect report - OEL-918
  src/components/bcl-form/__snapshots__/form.test.js.snap
  src/components/bcl-select/__snapshots__/select.test.js.snap
  src/components/bcl-select/select.html.twig
  src/data/select/data.js
  src/data/select/dataMultiselect.js
Labels: tag: enhancement

#185 feat(search): Updates on search page - OEL-914
  src/components/bcl-button/button.html.twig
  src/components/bcl-twig-templates/package.json
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-search/dataSearch.js
  src/compositions/bcl-search/package.json
  src/compositions/bcl-search/search.html.twig
  src/compositions/bcl-search/search.story.js
  src/compositions/bcl-search/search.test.js
  src/data/header/data--no-form.js
Labels: tag: new feature
