Repository openeuropa/bootstrap-component-library, pull requests merged in 2021-09, with the labels that each got.

#52 feat(figma-links): Added Figma links - Front 3042
  src/compositions/bcl-search/search.story.js
  src/compositions/bcl-user-listing/user-listing.story.js
Labels: tag: internal

#53 feat(form-sidebar): Changed user listing and search sidebar to use form component - FRONT-3056
  src/components/bcl-form-input/form-input.html.twig
  src/components/bcl-form/form.html.twig
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-search/dataSearch.js
  src/compositions/bcl-search/package.json
  src/compositions/bcl-search/search-offcanvas.html.twig
  src/compositions/bcl-user-listing/__snapshots__/user-listing.test.js.snap
  src/compositions/bcl-user-listing/dataUserListing.js
  src/compositions/bcl-user-listing/package.json
  src/compositions/bcl-user-listing/user-listing-offcanvas.html.twig
Labels: tag: enhancement

#51 feat(user-view): Added user view - Front 2901
  src/components/bcl-card/card.html.twig
  src/components/bcl-twig-templates/package.json
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-search/dataSearch.js
  src/compositions/bcl-search/search.html.twig
  src/compositions/bcl-user-listing/__snapshots__/user-listing.test.js.snap
  src/compositions/bcl-user-listing/dataUserListing.js
  src/compositions/bcl-user-listing/user-listing.html.twig
  src/compositions/bcl-user-view/__snapshots__/user-view.test.js.snap
  src/compositions/bcl-user-view/dataUserView.js
  src/compositions/bcl-user-view/package.json
  src/compositions/bcl-user-view/user-view.html.twig
  src/compositions/bcl-user-view/user-view.story.js
  src/compositions/bcl-user-view/user-view.test.js
  src/data/card/dataHorizontal.js
Labels: tag: breaking change

#55 chore: Removing ECL, using ecl header as default, updating compositions
  package.json
  src/components/bcl-header/header.story.js
  src/compositions/bcl-header/.npmignore
  src/compositions/bcl-header/__snapshots__/header.test.js.snap
  src/compositions/bcl-header/header.html.twig
  src/compositions/bcl-header/header.story.js
  src/compositions/bcl-header/header.test.js
  src/compositions/bcl-header/package.json
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-search/dataSearch.js
  src/compositions/bcl-search/search.html.twig
  src/compositions/bcl-search/search.story.js
  src/compositions/bcl-user-listing/__snapshots__/user-listing.test.js.snap
  src/compositions/bcl-user-listing/dataUserListing.js
  src/compositions/bcl-user-listing/user-listing.html.twig
  src/compositions/bcl-user-listing/user-listing.story.js
  src/compositions/bcl-user-view/__snapshots__/user-view.test.js.snap
  src/compositions/bcl-user-view/dataUserView.js
  src/compositions/bcl-user-view/user-view.html.twig
  src/compositions/bcl-user-view/user-view.story.js
  src/data/header/data-ecl.js
  src/themes/default/src/scss/_header.scss
  src/themes/ecl/.npmignore
  src/themes/ecl/bcl-builder.config.js
  src/themes/ecl/icons/bootstrap-icons.svg
  src/themes/ecl/package.json
  src/themes/ecl/src/js/index.esm.js
  src/themes/ecl/src/js/index.umd.js
  src/themes/ecl/src/scss/_header.scss
  src/themes/ecl/src/scss/_language-list.scss
  src/themes/ecl/src/scss/base/_variables.scss
  src/themes/ecl/src/scss/oe-bcl-ecl.scss
  src/themes/ecl/src/stories/bcl-stories.js
  src/themes/ecl/src/templates/bcl-templates.js
  src/themes/ecl/storybook/.project.json
  src/themes/ecl/storybook/.storybook/preview-head.html
  src/themes/ecl/storybook/bcl-builder.config.js
  src/themes/ecl/storybook/package.json
  src/themes/ecl/storybook/project.json
  static/index.html
Labels: tag: internal, process: review needed

#54 feat(user-edit): Added composition of user edit - Front 3040
  src/components/bcl-form-input/form-input.html.twig
  src/components/bcl-navigation/navigation.html.twig
  src/components/bcl-textarea/__snapshots__/textarea.test.js.snap
  src/components/bcl-textarea/textarea.html.twig
  src/components/bcl-textarea/textarea.story.js
  src/components/bcl-textarea/textarea.test.js
  src/components/bcl-twig-templates/package.json
  src/compositions/bcl-user-edit/__snapshots__/user-edit.test.js.snap
  src/compositions/bcl-user-edit/dataUserEdit.js
  src/compositions/bcl-user-edit/edit-contents.html.twig
  src/compositions/bcl-user-edit/package.json
  src/compositions/bcl-user-edit/user-edit.html.twig
  src/compositions/bcl-user-edit/user-edit.story.js
  src/compositions/bcl-user-edit/user-edit.test.js
Labels: tag: new feature

#57 chore(deps): updates 09-11-21
  .storybook/preview.js
  bootstrap/package.json
  builder/package.json
  package.json
  src/themes/default/storybook/.storybook/preview.js
  src/themes/default/storybook/package.json
  src/themes/joinup/storybook/package.json
  yarn.lock
Labels: tag: internal

#58 feat(Update-scripts): Moved script inits - FRONT-3129
  .storybook/preview-head.html
  src/components/bcl-button/button.story.js
  src/components/bcl-link/link.story.js
  src/components/bcl-offcanvas/offcanvas.story.js
  src/components/bcl-scrollspy/scrollspy.story.js
  src/components/bcl-select/select.story.js
  src/components/bcl-toasts/toasts.story.js
  src/compositions/bcl-search/search.story.js
  src/themes/default/storybook/.storybook/preview-head.html
  src/themes/joinup/storybook/.storybook/preview-head.html
Labels: tag: new feature

#59 chore(size-limit): Adding basic size limits checks in the ci
  .github/workflows/ci.yml
  .size-limit.json
  package.json
  yarn.lock
Labels: tag: internal

#62 fix(button-group): Reset all btn-group styles when changing vertical state - FRONT-3166
  src/components/bcl-button-group/button-group.story.js
Labels: tag: bug fix

#66 feat(Navbar): Change color of the search button - FRONT-3170
  src/components/bcl-navbar/__snapshots__/navbar.test.js.snap
  src/data/navbar/data.js
Labels: tag: internal

#61 feat(links block): Add composition of links block - Front 3136
  .storybook/preview.js
  src/components/bcl-twig-templates/package.json
  src/compositions/bcl-links-block/__snapshots__/links-block.test.js.snap
  src/compositions/bcl-links-block/dataLinksBlock.js
  src/compositions/bcl-links-block/links-block.html.twig
  src/compositions/bcl-links-block/links-block.story.js
  src/compositions/bcl-links-block/links-block.test.js
  src/compositions/bcl-links-block/package.json
  src/themes/default/src/scss/_variables.scss
  src/themes/default/src/scss/oe-bcl-default.scss
Labels: tag: new feature, process: review needed

#67 feat(variables): Added new colors. - FRONT-3180
  src/themes/default/src/scss/_variables.scss
Labels: tag: new feature

#71 feat(social media follow): Add social media follow paragraph - Front 3140
  src/components/bcl-twig-templates/package.json
  src/compositions/bcl-links-block/__snapshots__/links-block.test.js.snap
  src/compositions/bcl-links-block/dataLinksBlock.js
  src/compositions/bcl-links-block/dataSocialMedia.js
  src/compositions/bcl-links-block/links-block.html.twig
  src/compositions/bcl-links-block/links-block.story.js
Labels: tag: new feature, process: review needed

#73 feat(spinner): added large size - FRONT-3168
  src/components/bcl-spinner/__snapshots__/spinner.test.js.snap
  src/components/bcl-spinner/spinner.html.twig
  src/components/bcl-spinner/spinner.story.js
  src/components/bcl-spinner/spinner.test.js
  src/data/button/spinnerData.js
  src/themes/default/src/scss/_spinners.scss
  src/themes/default/src/scss/oe-bcl-default.scss
  src/themes/joinup/src/scss/oe-bcl-joinup.scss
Labels: tag: new feature

#60 feat(footer): Added composition of footer - Front 3064
  src/components/bcl-twig-templates/package.json
  src/compositions/bcl-footer/.npmignore
  src/compositions/bcl-footer/__snapshots__/footer.test.js.snap
  src/compositions/bcl-footer/footer.html.twig
  src/compositions/bcl-footer/footer.story.js
  src/compositions/bcl-footer/footer.test.js
  src/compositions/bcl-footer/package.json
  src/data/footer/data-ec.js
  src/data/footer/data.js
  src/data/footer/package.json
  src/themes/default/src/scss/_footer.scss
  src/themes/default/src/scss/_variables.scss
  src/themes/default/src/scss/oe-bcl-default.scss
Labels: tag: new feature, process: review needed

#75 chore(deps): Updates - 28/09/21
  builder/package.json
  package.json
  src/themes/default/package.json
  src/themes/default/src/scss/_multiselect.scss
  src/themes/default/storybook/package.json
  src/themes/joinup/package.json
  src/themes/joinup/storybook/package.json
  yarn.lock
Labels: tag: internal

#69 feat(alert): Adding icons to the alert component - FRONT-3176
  src/components/bcl-alert/__snapshots__/alert.test.js.snap
  src/components/bcl-alert/alert.html.twig
  src/components/bcl-alert/alert.story.js
  src/data/alert/data.js
Labels: tag: enhancement

#64 fix(form-input): Range input type renders correctly - front-3173
  src/components/bcl-form-input/__snapshots__/form-input.test.js.snap
  src/components/bcl-form-input/form-input.html.twig
  src/components/bcl-form-input/form-input.test.js
Labels: tag: bug fix, process: review needed

#77 fix(badge): Fixing close icon display issue when the badge is a link - FRONT-3214
  src/components/bcl-badge/__snapshots__/badge.test.js.snap
  src/components/bcl-badge/badge.test.js
  src/themes/default/src/scss/_badge.scss
Labels: tag: bug fix, process: review needed

#76 feat(joinup): Fine-tune btn-light - FRONT-3210
  src/themes/joinup/src/scss/_buttons.scss
Labels: tag: enhancement, process: review needed

#80 feat(card): Add default right margin for badges in the cards - FRONT-3215
  src/components/bcl-card/__snapshots__/card.test.js.snap
  src/components/bcl-card/card.html.twig
  src/data/card/data.js
Labels: tag: enhancement
