Repository openeuropa/bootstrap-component-library, pull requests merged in 2021-10, with the labels that each got.

#81 feat(Sizes): Redo form elements sizes. - FRONT-3229
  src/components/bcl-form-input/__snapshots__/form-input.test.js.snap
  src/components/bcl-form-input/form-input.html.twig
  src/components/bcl-form-input/form-input.story.js
  src/components/bcl-form/__snapshots__/form.test.js.snap
  src/components/bcl-select/__snapshots__/select.test.js.snap
  src/components/bcl-select/select.html.twig
  src/components/bcl-select/select.story.js
  src/components/bcl-textarea/__snapshots__/textarea.test.js.snap
  src/components/bcl-textarea/textarea.html.twig
  src/components/bcl-textarea/textarea.story.js
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-search/dataSearch.js
  src/compositions/bcl-user-edit/__snapshots__/user-edit.test.js.snap
  src/compositions/bcl-user-edit/dataUserEdit.js
  src/compositions/bcl-user-listing/__snapshots__/user-listing.test.js.snap
  src/compositions/bcl-user-listing/dataUserListing.js
  src/data/form-input/data.js
  src/data/form/data-disabled.js
  src/data/list-group/data.js
  src/data/list-group/orderedData.js
  src/data/select/data.js
  src/data/textarea/data.js
  src/themes/default/src/scss/_input.scss
  src/themes/default/src/scss/_multiselect.scss
  src/themes/default/src/scss/_variables.scss
  src/themes/default/src/scss/oe-bcl-default.scss
  tools/story-utils/index.js
Labels: tag: new feature, process: review needed

#82 chore(deps): updates - 04-10-21
  builder/package.json
  package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/storybook/package.json
  yarn.lock
Labels: tag: internal

#74 feat(user-small-teaser): Create composition for small user view - FRONT-3175
  src/compositions/bcl-user-listing/__snapshots__/user-listing.test.js.snap
  src/compositions/bcl-user-listing/data-user-listing.js
  src/compositions/bcl-user-listing/user-listing.html.twig
  src/compositions/bcl-user-listing/user-listing.story.js
  src/compositions/bcl-user-listing/user-listing.test.js
  src/compositions/bcl-user-view/__snapshots__/user-view.test.js.snap
  src/compositions/bcl-user-view/dataUserViewCompact.js
  src/compositions/bcl-user-view/user-view-compact.html.twig
  src/compositions/bcl-user-view/user-view.story.js
  src/compositions/bcl-user-view/user-view.test.js
Labels: tag: new feature

#70 feat(multiselect): Bug fix and large size. - FRONT-3178
  src/components/bcl-select/__snapshots__/select.test.js.snap
  src/components/bcl-select/select.html.twig
  src/data/select/dataMultiselect.js
  src/themes/default/src/scss/_multiselect.scss
Labels: tag: enhancement, process: review needed

#65 fix(card): Header and footer, improving stories - FRONT-3165
  src/components/bcl-card-layout/__snapshots__/card-layout.test.js.snap
  src/components/bcl-card-layout/card-layout.story.js
  src/components/bcl-card/__snapshots__/card.test.js.snap
  src/components/bcl-card/card.html.twig
  src/components/bcl-card/card.story.js
  src/compositions/bcl-user-listing/__snapshots__/user-listing.test.js.snap
  src/data/card-layout/dataMasonry.js
Labels: tag: enhancement, process: review needed

#68 feat(tooltip): Adding control for tooltip position in button and link - FRONT-3172
  src/components/bcl-button/__snapshots__/button.test.js.snap
  src/components/bcl-button/button.story.js
  src/components/bcl-link/__snapshots__/link.test.js.snap
  src/components/bcl-link/link.story.js
  src/data/button/tooltipData.js
  src/data/link/tooltipData.js
Labels: tag: enhancement, process: review needed

#72 feat(search): Added search - FRONT-3177
  .size-limit.json
  src/components/bcl-form-input/form-input.story.js
  src/compositions/bcl-search-form/__snapshots__/search-form.test.js.snap
  src/compositions/bcl-search-form/dataSearch.js
  src/compositions/bcl-search-form/dataSearchSubmit.js
  src/compositions/bcl-search-form/package.json
  src/compositions/bcl-search-form/search-form.html.twig
  src/compositions/bcl-search-form/search-form.story.js
  src/compositions/bcl-search-form/search-form.test.js
  src/themes/default/src/scss/_search-form.scss
  src/themes/default/src/scss/_variables.scss
  src/themes/default/src/scss/oe-bcl-default.scss
  src/themes/joinup/src/scss/base/_variables.scss
  src/themes/joinup/src/scss/oe-bcl-joinup.scss
Labels: tag: new feature

#84 feat(multiselect): Improvements - FRONT-3250
  src/components/bcl-select/select.story.js
  src/themes/default/src/scss/_multiselect.scss
  tools/story-utils/index.js
Labels: tag: enhancement

#79 fix(toasts): Improvements on the template - FRONT-3212
  src/components/bcl-toasts/__snapshots__/toasts.test.js.snap
  src/components/bcl-toasts/toasts.html.twig
  src/data/toasts/data-multiple.js
  src/data/toasts/data.js
Labels: tag: enhancement
