Repository openeuropa/bootstrap-component-library, pull requests merged in 2022-07, with the labels that each got.

#399 chore(deps): Updates 04-07-22
  package.json
  src/data/icon/package.json
  src/themes/default/package.json
  src/themes/joinup/package.json
  src/themes/ucpkn/package.json
  yarn.lock
Labels: tag: internal

#400 feat(listing): Listing image size parameter and cleanup - OEL-1810
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-listing/__snapshots__/listing.test.js.snap
  src/compositions/bcl-listing/data/listing--date.js
  src/compositions/bcl-listing/data/listing--profiles.js
  src/compositions/bcl-listing/listing.html.twig
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-person/__snapshots__/person.test.js.snap
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-project/data/data--listing.js
  src/compositions/bcl-publication/__snapshots__/publication.test.js.snap
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
Labels: tag: enhancement

#403 feat(data): Added new filter in sidebar of listings - OEL-1819
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-event/data/data--listing.js
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-news/data/data--listing.js
  src/compositions/bcl-procurement/__snapshots__/procurement.test.js.snap
  src/compositions/bcl-procurement/data/data--listing.js
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-project/data/data--listing.js
  src/compositions/bcl-publication/__snapshots__/publication.test.js.snap
  src/compositions/bcl-publication/data/data--listing.js
  src/compositions/bcl-vacancy/__snapshots__/vacancy.test.js.snap
  src/compositions/bcl-vacancy/data/data--listing.js
Labels: tag: enhancement, process: review needed

#404 chore(deps): Updates 11-07-22
  builder/package.json
  package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal

#401 feat(description-lists): Spacing reviewed - OEL-1812
  src/compositions/bcl-description-list/__snapshots__/description-list.test.js.snap
  src/compositions/bcl-description-list/description-list.html.twig
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-project-status/__snapshots__/project-status.test.js.snap
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-project/project-lists.html.twig
  src/themes/default/src/scss/_description_list.scss
Labels: tag: enhancement

#406 feat(paragraphs): Adding controls for optional title
  src/components/bcl-accordion/accordion.story.js
  src/components/bcl-blockquote/blockquote.html.twig
  src/components/bcl-blockquote/blockquote.story.js
  src/components/bcl-carousel/carousel.html.twig
  src/components/bcl-carousel/carousel.story.js
  src/compositions/bcl-banner/banner.story.js
  src/compositions/bcl-description-list/description-list.html.twig
  src/compositions/bcl-description-list/description-list.story.js
  src/compositions/bcl-fact-figures/__snapshots__/fact-figures.test.js.snap
  src/compositions/bcl-fact-figures/data.js
  src/compositions/bcl-fact-figures/fact-figures.story.js
  src/compositions/bcl-featured-media/__snapshots__/featured-media.test.js.snap
  src/compositions/bcl-featured-media/featured-media.html.twig
  src/compositions/bcl-featured-media/featured-media.story.js
  src/compositions/bcl-file/file.story.js
  src/compositions/bcl-gallery/gallery.story.js
  src/compositions/bcl-inpage-navigation/inpage-navigation.story.js
  src/compositions/bcl-links-block/links-block.story.js
  src/compositions/bcl-links-block/social-media.story.js
  src/compositions/bcl-listing/listing.story.js
  src/compositions/bcl-timeline/timeline.story.js
  tools/story-utils/index.js
Labels: tag: enhancement

#409 fix(language-switcher): Changing approach to fix layout when the number of items is too low - OEL-1849
  src/compositions/bcl-language-switcher/__snapshots__/language-switcher.test.js.snap
  src/compositions/bcl-language-switcher/language-switcher.html.twig
Labels: tag: enhancement, process: review needed

#407 feat(person): Adding file sub-section in details page - OEL-1848
  src/compositions/bcl-person/__snapshots__/person.test.js.snap
  src/compositions/bcl-person/data/data--details.js
  src/compositions/bcl-person/person.html.twig
Labels: tag: enhancement
