Repository openeuropa/bootstrap-component-library, pull requests merged in 2022-08, with the labels that each got.

#416 feat(cleanup): Removed extension from import of js files - OEL-1907
  src/components/bcl-accordion/accordion.story.js
  src/components/bcl-alert/alert.story.js
  src/components/bcl-alert/test-alert.story.js
  src/components/bcl-badge/badge.story.js
  src/components/bcl-badge/test-badge.story.js
  src/components/bcl-blockquote/blockquote.story.js
  src/components/bcl-breadcrumb/breadcrumb.story.js
  src/components/bcl-form-input/form-input.story.js
  src/components/bcl-icon/icon.story.js
  src/components/bcl-modal/modal.story.js
  src/components/bcl-navbar/navbar.story.js
  src/components/bcl-offcanvas/offcanvas.story.js
  src/components/bcl-placeholder/placeholder.story.js
  src/components/bcl-progress/progress.story.js
  src/components/bcl-select/select.story.js
  src/components/bcl-spinner/spinner.story.js
  src/components/bcl-table/table.story.js
  src/components/bcl-textarea/textarea.story.js
  src/components/bcl-toasts/toasts.story.js
  src/compositions/bcl-content-banner/content-banner.story.js
  src/compositions/bcl-date-block/date-block.story.js
  src/compositions/bcl-description-list/description-list.story.js
  src/compositions/bcl-fact-figures/fact-figures.story.js
  src/compositions/bcl-featured-media/featured-media.story.js
  src/compositions/bcl-footer/footer.story.js
  src/compositions/bcl-gallery/gallery.story.js
  src/compositions/bcl-icons-list/icons-list.story.js
  src/compositions/bcl-language-list/language-list.story.js
  src/compositions/bcl-language-switcher/language-switcher.story.js
  src/compositions/bcl-project-status/project-status.story.js
  src/compositions/bcl-project-status/project-status.test.js
  src/compositions/bcl-project/data/data.js
  src/compositions/bcl-recent-activities/recent-activities.story.js
  src/compositions/bcl-search-form/search-form.story.js
  src/compositions/bcl-subscription-block/subscription-block.story.js
  src/themes/ucpkn/src/stories/footer.story.js
Labels: tag: enhancement

#417 chore(bootstrap): Upgrading to 5.2 + other updates
  .size-limit.json
  bootstrap/package.json
  builder/package.json
  package.json
  src/components/bcl-carousel/__snapshots__/carousel.test.js.snap
  src/components/bcl-carousel/carousel.html.twig
  src/components/bcl-carousel/carousel.story.js
  src/components/bcl-carousel/carousel.test.js
  src/compositions/bcl-gallery/__snapshots__/gallery.test.js.snap
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/themes/default/bcl-builder.config.js
  src/themes/default/src/js/gallery/gallery.js
  src/themes/default/src/scss/oe-bcl-default.scss
  src/themes/default/storybook/package.json
  src/themes/joinup/bcl-builder.config.js
  src/themes/joinup/src/scss/oe-bcl-joinup.scss
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/bcl-builder.config.js
  src/themes/ucpkn/src/scss/oe-bcl-ucpkn.scss
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal, process: review needed

#413 feat(tests): Added missing tests for components - OEL-1889
  src/components/bcl-accordion/__snapshots__/accordion.test.js.snap
  src/components/bcl-accordion/accordion.test.js
  src/components/bcl-alert/__snapshots__/alert.test.js.snap
  src/components/bcl-alert/alert.test.js
  src/components/bcl-badge/__snapshots__/badge.test.js.snap
  src/components/bcl-badge/badge.test.js
  src/components/bcl-blockquote/__snapshots__/blockquote.test.js.snap
  src/components/bcl-blockquote/blockquote.test.js
  src/components/bcl-button-group/__snapshots__/button-group.test.js.snap
  src/components/bcl-button-group/button-group.test.js
  src/components/bcl-button/__snapshots__/button.test.js.snap
  src/components/bcl-button/button.test.js
  src/components/bcl-card-layout/__snapshots__/card-layout.test.js.snap
  src/components/bcl-card-layout/card-layout.test.js
  src/components/bcl-carousel/__snapshots__/carousel.test.js.snap
  src/components/bcl-carousel/carousel.test.js
  src/components/bcl-dropdown/__snapshots__/dropdown.test.js.snap
  src/components/bcl-dropdown/dropdown.test.js
  src/components/bcl-form/__snapshots__/form.test.js.snap
  src/components/bcl-form/form.test.js
  src/components/bcl-link/__snapshots__/link.test.js.snap
  src/components/bcl-link/link.test.js
  src/components/bcl-list-group/__snapshots__/list-group.test.js.snap
  src/components/bcl-list-group/list-group.test.js
  src/components/bcl-modal/__snapshots__/modal.test.js.snap
  src/components/bcl-modal/modal.test.js
  src/components/bcl-navbar/__snapshots__/navbar.test.js.snap
  src/components/bcl-navbar/navbar.test.js
  src/components/bcl-offcanvas/__snapshots__/offcanvas.test.js.snap
  src/components/bcl-offcanvas/offcanvas.test.js
  src/components/bcl-pagination/__snapshots__/pagination.test.js.snap
  src/components/bcl-pagination/pagination.test.js
  src/components/bcl-progress/__snapshots__/progress.test.js.snap
  src/components/bcl-progress/progress.test.js
  src/components/bcl-select/__snapshots__/select.test.js.snap
  src/components/bcl-select/select.test.js
  src/components/bcl-textarea/__snapshots__/textarea.test.js.snap
  src/components/bcl-textarea/textarea.test.js
Labels: tag: enhancement

#408 feat(header): collapsible top navbar, data refactoring - OEL-1847
  src/components/bcl-breadcrumb/__snapshots__/breadcrumb.test.js.snap
  src/components/bcl-navbar/navbar.html.twig
  src/compositions/bcl-contact-form/__snapshots__/contact-form.test.js.snap
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-glossary/__snapshots__/glossary.test.js.snap
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-header/__snapshots__/header.test.js.snap
  src/compositions/bcl-header/header.story.js
  src/compositions/bcl-landing-page/__snapshots__/landing-page.test.js.snap
  src/compositions/bcl-language-list/__snapshots__/language-list.test.js.snap
  src/compositions/bcl-language-list/data/data--ec.js
  src/compositions/bcl-multilingual/data/data--ec.js
  src/compositions/bcl-multilingual/data/data--eu.js
  src/compositions/bcl-multilingual/data/data--neutral.js
  src/compositions/bcl-multilingual/multilingual.story.js
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-page/__snapshots__/page.test.js.snap
  src/compositions/bcl-person/__snapshots__/person.test.js.snap
  src/compositions/bcl-procurement/__snapshots__/procurement.test.js.snap
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-publication/__snapshots__/publication.test.js.snap
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-subscription/__snapshots__/subscription.test.js.snap
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/compositions/bcl-vacancy/__snapshots__/vacancy.test.js.snap
  src/data/breadcrumb/data.js
  src/data/header/data--ec.js
  src/data/header/data--loggedIn.js
  src/data/header/data--modals.js
  src/data/header/data--navbar.js
  src/data/header/data--neutral.js
  src/data/header/data--no-form.js
  src/data/header/data--simple.js
  src/data/header/data--top-navbar.js
  src/data/header/data.js
  src/data/header/package.json
  src/themes/default/src/scss/_header.scss
  src/themes/ucpkn/src/scss/_header.scss
  src/themes/ucpkn/src/scss/oe-bcl-ucpkn.scss
Labels: tag: enhancement, process: review needed

#418 feat(bootstrap-5.2): Aligning components - OEL-1916
  src/components/bcl-list-group/__snapshots__/list-group.test.js.snap
  src/components/bcl-offcanvas/__snapshots__/offcanvas.test.js.snap
  src/components/bcl-offcanvas/offcanvas.html.twig
  src/components/bcl-offcanvas/offcanvas.test.js
  src/components/bcl-progress/__snapshots__/progress.test.js.snap
  src/components/bcl-progress/progress.html.twig
  src/compositions/bcl-base-templates/sidebar-search.html.twig
  src/compositions/bcl-content-banner/content-banner.story.js
  src/compositions/bcl-content-banner/data/data--action-button.js
  src/compositions/bcl-content-banner/data/data.js
  src/compositions/bcl-content-banner/test-content-banner.story.js
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-event/data/data--listing.js
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-group/data/data--list-content.js
  src/compositions/bcl-group/data/data--list-member.js
  src/compositions/bcl-group/data/data--list.js
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-news/data/data--listing.js
  src/compositions/bcl-person/__snapshots__/person.test.js.snap
  src/compositions/bcl-person/data/data--listing.js
  src/compositions/bcl-procurement/__snapshots__/procurement.test.js.snap
  src/compositions/bcl-procurement/data/data--listing.js
  src/compositions/bcl-project-status/__snapshots__/project-status.test.js.snap
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-project/data/data--listing.js
  src/compositions/bcl-publication/__snapshots__/publication.test.js.snap
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-search/data/data--search.js
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/compositions/bcl-user/data/data--user-listing.js
  src/compositions/bcl-vacancy/__snapshots__/vacancy.test.js.snap
  src/compositions/bcl-vacancy/data/data--listing.js
  src/data/list-group/data--ordered.js
  src/themes/default/src/scss/_bcl-offcanvas.scss
  src/themes/default/src/scss/_pagination.scss
  src/themes/default/src/scss/oe-bcl-default.scss
  src/themes/joinup/src/scss/oe-bcl-joinup.scss
  src/themes/ucpkn/src/scss/oe-bcl-ucpkn.scss
Labels: tag: breaking change

#420 feat(featured-image): Improvement on width image - OEL-1920
  src/compositions/bcl-featured-media/__snapshots__/featured-media.test.js.snap
  src/compositions/bcl-featured-media/data/data--image.js
  src/compositions/bcl-featured-media/featured-media.html.twig
  src/themes/default/src/scss/base/_utilities.scss
Labels: tag: enhancement

#421 chore(deps): Updates 05-08-22
  builder/package.json
  package.json
  src/data/icon/package.json
  src/themes/default/package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/package.json
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal

#422 chore(deps): Updates 08-08-22
  builder/package.json
  package.json
  src/themes/joinup/package.json
  yarn.lock
Labels: tag: internal

#423 feat(heading): Adding stories for heading(s) - OEL-1929
  src/components/bcl-heading/.npmignore
  src/components/bcl-heading/data/data--list.js
  src/components/bcl-heading/heading.story.js
Labels: tag: new feature

#424 feat(axe-tests): Added accessiblity tests - OEL-1923
  src/components/bcl-navigation/navigation.html.twig
  src/compositions/bcl-contact-form/__snapshots__/contact-form.test.js.snap
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-event/event.test.js
  src/compositions/bcl-fact-figures/fact-figures.test.js
  src/compositions/bcl-featured-media/featured-media.test.js
  src/compositions/bcl-glossary/__snapshots__/glossary.test.js.snap
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-group/group.test.js
  src/compositions/bcl-header/__snapshots__/header.test.js.snap
  src/compositions/bcl-inpage-navigation/inpage-navigation.test.js
  src/compositions/bcl-landing-page/__snapshots__/landing-page.test.js.snap
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-page/__snapshots__/page.test.js.snap
  src/compositions/bcl-page/data/data--files.js
  src/compositions/bcl-page/data/data.js
  src/compositions/bcl-page/page.test.js
  src/compositions/bcl-person/__snapshots__/person.test.js.snap
  src/compositions/bcl-person/person.test.js
  src/compositions/bcl-procurement/__snapshots__/procurement.test.js.snap
  src/compositions/bcl-procurement/data/data--content.js
  src/compositions/bcl-procurement/procurement.test.js
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-project/project.test.js
  src/compositions/bcl-publication/__snapshots__/publication.test.js.snap
  src/compositions/bcl-publication/publication.test.js
  src/compositions/bcl-recent-activities/recent-activities.test.js
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-search/search.test.js
  src/compositions/bcl-subscription/__snapshots__/subscription.test.js.snap
  src/compositions/bcl-subscription/subscription.test.js
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/compositions/bcl-user/data/data--form.js
  src/compositions/bcl-user/user.test.js
  src/compositions/bcl-vacancy/__snapshots__/vacancy.test.js.snap
  src/compositions/bcl-vacancy/data/data--details.js
  src/compositions/bcl-vacancy/data/data--listing.js
  src/compositions/bcl-vacancy/vacancy.test.js
  src/data/header/data--navbar.js
  src/data/header/data--no-form.js
Labels: tag: enhancement

#426 feat(content-banner): Fix container for banner inside tab panel - OEL-1935
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/compositions/bcl-user/data/data--form.js
  src/themes/default/src/scss/_banners.scss
Labels: tag: bug fix

#425 chore: Updating links to bs documentation
  src/components/bcl-accordion/accordion.story.js
  src/components/bcl-alert/alert.story.js
  src/components/bcl-badge/badge.story.js
  src/components/bcl-blockquote/blockquote.story.js
  src/components/bcl-breadcrumb/breadcrumb.story.js
  src/components/bcl-button-group/button-group.story.js
  src/components/bcl-button/button.story.js
  src/components/bcl-card-layout/card-layout.story.js
  src/components/bcl-card/card.story.js
  src/components/bcl-carousel/carousel.story.js
  src/components/bcl-dropdown/dropdown.story.js
  src/components/bcl-form-input/form-input.story.js
  src/components/bcl-form/form.story.js
  src/components/bcl-icon/icon.story.js
  src/components/bcl-link/link.story.js
  src/components/bcl-list-group/list-group.story.js
  src/components/bcl-modal/modal.story.js
  src/components/bcl-navbar/navbar.story.js
  src/components/bcl-navigation/navigation.story.js
  src/components/bcl-offcanvas/offcanvas.story.js
  src/components/bcl-pagination/pagination.story.js
  src/components/bcl-placeholder/placeholder.story.js
  src/components/bcl-progress/progress.story.js
  src/components/bcl-select/select.story.js
  src/components/bcl-spinner/spinner.story.js
  src/components/bcl-table/table.story.js
  src/components/bcl-toasts/toasts.story.js
  src/compositions/bcl-inpage-navigation/inpage-navigation.story.js
Labels: tag: documentation, process: review needed

#428 chore(storybook): Reverting to 6.5.9 to fix breaking error
  src/themes/default/storybook/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal

#433 chore(deps): Updates 17-08-22
  builder/package.json
  package.json
  src/compositions/bcl-project/project.test.js
  yarn.lock
Labels: tag: internal

#437 chore(deps): Updates 19-08-22
  builder/package.json
  tools/plugins/storybook-addon-code/package.json
  yarn.lock
Labels: tag: internal

#432 fix(user): Adding condition, using local variables in user compact - OEL-1945
  src/compositions/bcl-user/user-compact.html.twig
Labels: tag: bug fix, process: review needed

#441 chore(deps): Updates 29-08-22
  builder/package.json
  package.json
  src/components/bcl-card-layout/__snapshots__/card-layout.test.js.snap
  src/compositions/bcl-glossary/glossary.test.js
  src/compositions/bcl-user/user.test.js
  src/themes/default/storybook/package.json
  src/themes/joinup/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal

#439 chore(twig): Replacing spaceless tag with filter
  patches/twing+2.3.7.patch
  src/components/bcl-accordion/accordion.html.twig
  src/components/bcl-alert/alert.html.twig
  src/components/bcl-badge/badge.html.twig
  src/components/bcl-blockquote/blockquote.html.twig
  src/components/bcl-breadcrumb/breadcrumb.html.twig
  src/components/bcl-button-group/button-group.html.twig
  src/components/bcl-button/button.html.twig
  src/components/bcl-card-layout/card-layout.html.twig
  src/components/bcl-card/card.html.twig
  src/components/bcl-carousel/carousel.html.twig
  src/components/bcl-dropdown/dropdown.html.twig
  src/components/bcl-form-input/form-input.html.twig
  src/components/bcl-form/form.html.twig
  src/components/bcl-heading/heading.html.twig
  src/components/bcl-icon/icon.html.twig
  src/components/bcl-link/link.html.twig
  src/components/bcl-list-group/list-group.html.twig
  src/components/bcl-modal/modal.html.twig
  src/components/bcl-navbar/navbar.html.twig
  src/components/bcl-navigation/navigation.html.twig
  src/components/bcl-offcanvas/offcanvas.html.twig
  src/components/bcl-pagination/pagination.html.twig
  src/components/bcl-placeholder/placeholder.html.twig
  src/components/bcl-progress/progress.html.twig
  src/components/bcl-select/select.html.twig
  src/components/bcl-spinner/spinner.html.twig
  src/components/bcl-table/table.html.twig
  src/components/bcl-textarea/textarea.html.twig
  src/components/bcl-toasts/toasts.html.twig
  src/compositions/bcl-banner/banner.html.twig
  src/compositions/bcl-base-templates/content-type.html.twig
  src/compositions/bcl-colors/colors.html.twig
  src/compositions/bcl-content-banner/content-banner.html.twig
  src/compositions/bcl-date-block/date-block.html.twig
  src/compositions/bcl-description-list/description-list.html.twig
  src/compositions/bcl-fact-figures/fact-figures.html.twig
  src/compositions/bcl-featured-media/featured-media.html.twig
  src/compositions/bcl-file/file.html.twig
  src/compositions/bcl-footer/footer.html.twig
  src/compositions/bcl-gallery/gallery.html.twig
  src/compositions/bcl-header/header.html.twig
  src/compositions/bcl-icons-list/icons-list.html.twig
  src/compositions/bcl-inpage-navigation/inpage-navigation.html.twig
  src/compositions/bcl-language-list/language-list-grid.html.twig
  src/compositions/bcl-language-list/language-list.html.twig
  src/compositions/bcl-language-switcher/language-switcher.html.twig
  src/compositions/bcl-links-block/links-block.html.twig
  src/compositions/bcl-listing/listing.html.twig
  src/compositions/bcl-project-status/project-contributions.html.twig
  src/compositions/bcl-project-status/project-status.html.twig
  src/compositions/bcl-project/project-lists.html.twig
  src/compositions/bcl-recent-activities/recent-activities.html.twig
  src/compositions/bcl-search-form/search-form.html.twig
  src/compositions/bcl-subscription-block/subscription-block.html.twig
  src/compositions/bcl-timeline/timeline.html.twig
  src/compositions/bcl-user/user-compact.html.twig
Labels: tag: enhancement

#440 feat(icons): Adding mortarboard icons - OEL-1977
  src/themes/default/src/icons/icons.js
Labels: tag: enhancement

#442 feat(description-list): Adapting markup - OEL-1986
  src/compositions/bcl-description-list/__snapshots__/description-list.test.js.snap
  src/compositions/bcl-description-list/description-list.html.twig
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-event/event.test.js
  src/compositions/bcl-procurement/__snapshots__/procurement.test.js.snap
  src/compositions/bcl-project-status/__snapshots__/project-status.test.js.snap
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-vacancy/__snapshots__/vacancy.test.js.snap
Labels: tag: enhancement
