Repository openeuropa/bootstrap-component-library, pull requests merged in 2022-04, with the labels that each got.

#310 feat(semantic-color): Added semantic colors - OEL-1365
  src/compositions/bcl-colors/colors.html.twig
  src/compositions/bcl-colors/colors.story.js
  src/compositions/bcl-colors/package.json
  src/themes/default/src/scss/base/_colors.scss
  src/themes/default/src/scss/base/_utilities.scss
Labels: tag: new feature, process: review needed

#316 feat(data-files): Import bridge file - OEL-1330
  src/compositions/bcl-base-templates/data/content-page.js
  src/compositions/bcl-base-templates/data/layout.js
  src/compositions/bcl-base-templates/data/listing-page.js
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-event/event.story.js
  src/compositions/bcl-event/event.test.js
  src/compositions/bcl-group/group.story.js
  src/compositions/bcl-group/group.test.js
  src/compositions/bcl-landing-page/landing-page.story.js
  src/compositions/bcl-landing-page/landing-page.test.js
  src/compositions/bcl-multilingual/multilingual.story.js
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-news/news.story.js
  src/compositions/bcl-news/news.test.js
  src/compositions/bcl-page/page.story.js
  src/compositions/bcl-page/page.test.js
  src/compositions/bcl-person/__snapshots__/person.test.js.snap
  src/compositions/bcl-person/person.story.js
  src/compositions/bcl-person/person.test.js
  src/compositions/bcl-project/project.story.js
  src/compositions/bcl-project/project.test.js
  src/compositions/bcl-search/search.story.js
  src/compositions/bcl-search/search.test.js
  src/compositions/bcl-subscription/subscription.story.js
  src/compositions/bcl-subscription/subscription.test.js
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/compositions/bcl-user/user.story.js
  src/compositions/bcl-user/user.test.js
Labels: tag: enhancement, process: review needed

#317 feat(alert): Styles udpates - OEL-1391
  src/components/bcl-alert/__snapshots__/alert.test.js.snap
  src/components/bcl-alert/alert.html.twig
  src/compositions/bcl-contact-form/__snapshots__/contact-form.test.js.snap
  src/compositions/bcl-language-switcher/__snapshots__/language-switcher.test.js.snap
  src/compositions/bcl-subscription/__snapshots__/subscription.test.js.snap
  src/data/alert/data.js
  src/themes/default/src/scss/base/_colors.scss
  src/themes/default/src/scss/base/_utilities.scss
Labels: tag: enhancement

#319 fix(file): Fixing wrong condition - OEL-1406
  src/compositions/bcl-file/file.html.twig
Labels: tag: bug fix, process: review needed

#325 feat(project): Added main contributor - OEL-1399
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-project/data/data--extra-details.js
  src/compositions/bcl-project/data/data--lists.js
  src/compositions/bcl-project/data/data.js
  src/compositions/bcl-project/data/ucpkn/data--extra-details.js
  src/compositions/bcl-project/data/ucpkn/data--lists.js
  src/compositions/bcl-project/data/ucpkn/data.js
  src/compositions/bcl-project/package.json
  src/compositions/bcl-project/project-lists.html.twig
  src/compositions/bcl-project/project.html.twig
  src/compositions/bcl-project/project.story.js
  src/compositions/bcl-project/project.test.js
  src/themes/ucpkn/src/stories/project.story.js
Labels: tag: enhancement

#324 feat(publication): Added publication - OEL-1398
  src/compositions/bcl-publication/.npmignore
  src/compositions/bcl-publication/__snapshots__/publication.test.js.snap
  src/compositions/bcl-publication/data/data--extra-details.js
  src/compositions/bcl-publication/data/data--listing.js
  src/compositions/bcl-publication/data/data.js
  src/compositions/bcl-publication/package.json
  src/compositions/bcl-publication/publication.html.twig
  src/compositions/bcl-publication/publication.story.js
  src/compositions/bcl-publication/publication.test.js
Labels: tag: new feature

#329 chore(deps): updates 13-04-22
  builder/package.json
  package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/package.json
  tools/plugins/storybook-addon-code/package.json
  yarn.lock
Labels: tag: internal

#333 chore(deps): Updates 19-04-22
  builder/package.json
  package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/package.json
  tools/plugins/storybook-addon-code/package.json
  yarn.lock
Labels: tag: internal

#331 feat(page-titles): Added titles for features - OEL-1466
  src/compositions/bcl-base-templates/data/content-page.js
  src/compositions/bcl-content-banner/content-banner.html.twig
  src/compositions/bcl-content-banner/data/data--page-title.js
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-event/event.story.js
  src/compositions/bcl-event/event.test.js
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-group/group.story.js
  src/compositions/bcl-group/group.test.js
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-news/news.story.js
  src/compositions/bcl-news/news.test.js
  src/compositions/bcl-person/__snapshots__/person.test.js.snap
  src/compositions/bcl-person/person.story.js
  src/compositions/bcl-person/person.test.js
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-project/project.story.js
  src/compositions/bcl-project/project.test.js
  src/compositions/bcl-publication/__snapshots__/publication.test.js.snap
  src/compositions/bcl-publication/publication.story.js
  src/compositions/bcl-publication/publication.test.js
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/compositions/bcl-user/user.story.js
  src/compositions/bcl-user/user.test.js
Labels: tag: enhancement, process: review needed

#328 feat(headers): Added subthemes header - OEL-1437
  package.json
  src/compositions/bcl-base-templates/data/layout.js
  src/compositions/bcl-event/event.story.js
  src/compositions/bcl-event/event.test.js
  src/compositions/bcl-group/group.story.js
  src/compositions/bcl-group/group.test.js
  src/compositions/bcl-landing-page/landing-page.story.js
  src/compositions/bcl-landing-page/landing-page.test.js
  src/compositions/bcl-multilingual/multilingual.story.js
  src/compositions/bcl-news/news.story.js
  src/compositions/bcl-news/news.test.js
  src/compositions/bcl-page/page.story.js
  src/compositions/bcl-page/page.test.js
  src/compositions/bcl-person/person.story.js
  src/compositions/bcl-person/person.test.js
  src/compositions/bcl-project/project.story.js
  src/compositions/bcl-project/project.test.js
  src/compositions/bcl-publication/publication.story.js
  src/compositions/bcl-publication/publication.test.js
  src/compositions/bcl-search/search.story.js
  src/compositions/bcl-search/search.test.js
  src/compositions/bcl-subscription/subscription.story.js
  src/compositions/bcl-subscription/subscription.test.js
  src/compositions/bcl-user/user.story.js
  src/compositions/bcl-user/user.test.js
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/src/stories/bcl-stories.js
  src/themes/ucpkn/src/stories/footer.story.js
  src/themes/ucpkn/src/stories/header.story.js
  src/themes/ucpkn/src/stories/landing-page.story.js
  src/themes/ucpkn/src/stories/project.story.js
  src/themes/ucpkn/storybook/package.json
Labels: tag: enhancement

#330 feat(vacancy): Vacancy feature - OEL-1454
  src/compositions/bcl-vacancy/__snapshots__/vacancy.test.js.snap
  src/compositions/bcl-vacancy/data/data--listing.js
  src/compositions/bcl-vacancy/data/data--sidebar-details.js
  src/compositions/bcl-vacancy/data/data.js
  src/compositions/bcl-vacancy/package.json
  src/compositions/bcl-vacancy/vacancy.html.twig
  src/compositions/bcl-vacancy/vacancy.story.js
  src/compositions/bcl-vacancy/vacancy.test.js
Labels: tag: new feature, process: review needed

#337 chore(deps): Updates 25-04-22
  builder/package.json
  package.json
  src/themes/default/package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/package.json
  src/themes/ucpkn/storybook/package.json
  tools/plugins/storybook-addon-code/package.json
  yarn.lock
Labels: tag: internal

#339 chore(semantic pr): Using github action
  .github/workflows/ci.yml
Labels: tag: internal
