Repository openeuropa/bootstrap-component-library, pull requests merged in 2022-02, with the labels that each got.

#244 chore: Using node 16, gallium
  .github/workflows/preview_tag.yml
  .nvmrc
  bootstrap/package.json
  builder/package.json
  yarn.lock
Labels: tag: internal

#251 feat(multilanguage): Added badge - OEL-1084
  src/compositions/bcl-language-list/language-list.story.js
Labels: tag: enhancement

#248 fix(description-list): Fix accessibility issue - OEL-1115
  src/compositions/bcl-description-list/__snapshots__/description-list.test.js.snap
  src/compositions/bcl-description-list/description-list.html.twig
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
Labels: tag: bug fix

#252 feat(project): Add circular progress bar for project status - OEL-1137
  src/compositions/bcl-description-list/description-list.html.twig
  src/compositions/bcl-project-status/__snapshots__/project-status.test.js.snap
  src/compositions/bcl-project-status/data/data--closed.js
  src/compositions/bcl-project-status/data/data--ongoing.js
  src/compositions/bcl-project-status/data/data--planned.js
  src/compositions/bcl-project-status/project-status.html.twig
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-project/data/data--chart.js
  src/compositions/bcl-project/project.html.twig
  src/compositions/bcl-project/project.story.js
  src/compositions/bcl-project/project.test.js
  src/themes/default/src/scss/_circular-progress-bar.scss
  src/themes/default/src/scss/base/_utilities.scss
  src/themes/default/src/scss/base/_variables.scss
  src/themes/default/src/scss/oe-bcl-default.scss
Labels: tag: new feature, process: review needed

#253 feat(data-multilingual): Updated data for multilingual - OEL-1084
  src/compositions/bcl-contact-form/__snapshots__/contact-form.test.js.snap
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-landing-page/__snapshots__/landing-page.test.js.snap
  src/compositions/bcl-page/__snapshots__/page.test.js.snap
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/data/header/data--no-form.js
  src/data/header/data--simple.js
Labels: tag: bug fix, process: review needed

#259 chore(dev): Adding start-dev script, fixing start
  docs/developing.md
  package.json
Labels: tag: internal

#250 feat(card-layout): Create block in the card_layout template - OEL-1126
  src/components/bcl-card-layout/card-layout.html.twig
Labels: tag: enhancement

#249 feat(card): Create block in the card template - OEL-1125
  src/components/bcl-card/card.html.twig
Labels: tag: enhancement, process: review needed

#260 feat(navbar): Add branding, navigation and right blocks - OEL-1108
  src/components/bcl-navbar/navbar.html.twig
Labels: tag: enhancement

#266 chore(deps): updates 14-02-22
  builder/package.json
  package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal

#265 chore: Rewriting dev toolchains
  docs/developing.md
  package.json
  scripts/watch.js
  src/themes/default/package.json
  src/themes/joinup/package.json
  src/themes/ucpkn/package.json
  yarn.lock
Labels: tag: internal, process: review needed

#268 feat(project): Add circular progress bar for project status - OEL-1137
  src/compositions/bcl-description-list/description-list.html.twig
  src/compositions/bcl-project-status/__snapshots__/project-status.test.js.snap
  src/compositions/bcl-project-status/data/data--closed.js
  src/compositions/bcl-project-status/data/data--ongoing.js
  src/compositions/bcl-project-status/data/data--planned.js
  src/compositions/bcl-project-status/project-status.html.twig
  src/compositions/bcl-project-status/project-status.story.js
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-project/data/data--chart.js
  src/compositions/bcl-project/project.html.twig
  src/compositions/bcl-project/project.story.js
  src/compositions/bcl-project/project.test.js
  src/themes/default/src/scss/_circular-progress-bar.scss
  src/themes/default/src/scss/base/_utilities.scss
  src/themes/default/src/scss/base/_variables.scss
  src/themes/default/src/scss/oe-bcl-default.scss
  src/themes/joinup/src/scss/oe-bcl-joinup.scss
  src/themes/ucpkn/src/scss/oe-bcl-ucpkn.scss
Labels: tag: new feature

#258 fix(icons): Replace icons_path to icon_path parameters - OEL-1141
  src/components/bcl-alert/alert.html.twig
  src/components/bcl-alert/alert.story.js
  src/components/bcl-badge/badge.html.twig
  src/components/bcl-badge/badge.story.js
  src/components/bcl-breadcrumb/breadcrumb.html.twig
  src/components/bcl-breadcrumb/breadcrumb.story.js
  src/compositions/bcl-contact-form/data/data-error.js
  src/compositions/bcl-contact-form/data/data-success.js
  src/compositions/bcl-event/data/data-listing.js
  src/compositions/bcl-fact-figures/data/data.js
  src/compositions/bcl-fact-figures/fact-figures.html.twig
  src/compositions/bcl-fact-figures/fact-figures.story.js
  src/compositions/bcl-group/data.js
  src/compositions/bcl-language-list/data/data--ec.js
  src/compositions/bcl-language-list/data/data--eu.js
  src/compositions/bcl-language-list/data/data--neutral.js
  src/compositions/bcl-language-list/data/data-modal.js
  src/compositions/bcl-language-list/language-list-grid.html.twig
  src/compositions/bcl-language-list/language-list-modal.html.twig
  src/compositions/bcl-language-list/language-list.html.twig
  src/compositions/bcl-multilingual/data/data--ec.js
  src/compositions/bcl-multilingual/data/data--eu.js
  src/compositions/bcl-multilingual/data/data--neutral.js
  src/compositions/bcl-news/data/data_listing.js
  src/compositions/bcl-project/data/data_listing.js
  src/compositions/bcl-search/dataSearch.js
  src/compositions/bcl-subscription/data/data_modal.js
  src/compositions/bcl-timeline/dataDefault.js
  src/compositions/bcl-timeline/timeline.html.twig
  src/compositions/bcl-timeline/timeline.story.js
  src/compositions/bcl-user/data-user-listing.js
  src/data/alert/data.js
  src/data/breadcrumb/data.js
  src/data/header/data--neutral.js
  src/data/header/data--no-form.js
  src/data/header/data--simple.js
  src/data/header/data-ec.js
  src/data/header/data.js
Labels: tag: breaking change

#270 chore(deps): Updates 18-02-22
  builder/package.json
  package.json
  src/data/icon/package.json
  src/themes/default/package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/package.json
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal

#271 fix(modal): Aria-labelledby to aria-label - OEL-1179
  src/components/bcl-modal/__snapshots__/modal.test.js.snap
  src/components/bcl-modal/modal.html.twig
  src/compositions/bcl-contact-form/__snapshots__/contact-form.test.js.snap
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-header/__snapshots__/header.test.js.snap
  src/compositions/bcl-landing-page/__snapshots__/landing-page.test.js.snap
  src/compositions/bcl-language-list/__snapshots__/language-list.test.js.snap
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-page/__snapshots__/page.test.js.snap
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-subscription/__snapshots__/subscription.test.js.snap
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
Labels: tag: enhancement

#269 feat(banner): Aspect ratio banner - OEL-1183
  src/themes/default/src/scss/_banners.scss
Labels: tag: enhancement

#274 feat(placeholder): Reset em placeholder styles - OEL-1184
  src/components/bcl-alert/__snapshots__/alert.test.js.snap
  src/data/alert/data.js
  src/themes/default/src/scss/_reset.scss
Labels: tag: enhancement
