Repository openeuropa/bootstrap-component-library, pull requests merged in 2022-09, with the labels that each got.

#445 chore(deps): Updates 02-09-22
  builder/package.json
  package.json
  src/data/icon/package.json
  src/themes/default/package.json
  src/themes/joinup/package.json
  src/themes/ucpkn/package.json
  yarn.lock
Labels: tag: internal

#446 feat(file): Title new line on file card component - OEL-2013
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-file/__snapshots__/file.test.js.snap
  src/compositions/bcl-file/file.html.twig
  src/compositions/bcl-glossary/__snapshots__/glossary.test.js.snap
  src/compositions/bcl-page/__snapshots__/page.test.js.snap
  src/compositions/bcl-person/__snapshots__/person.test.js.snap
  src/compositions/bcl-procurement/__snapshots__/procurement.test.js.snap
  src/compositions/bcl-publication/__snapshots__/publication.test.js.snap
  src/compositions/bcl-vacancy/__snapshots__/vacancy.test.js.snap
Labels: tag: enhancement

#448 chore(deps): Updates 12-09-22
  bootstrap/package.json
  builder/package.json
  package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal

#449 chore(deps): Storybook 6.5.11
  CHANGELOG.md
  builder/package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/package.json
  tools/plugins/storybook-addon-code/package.json
  yarn.lock
Labels: tag: internal

#452 chore(deps): Storybook 6.5.12
  builder/package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/package.json
  tools/plugins/storybook-addon-code/package.json
  yarn.lock
Labels: tag: internal

#451 fix(carousel): Fixing condition for caption rendering - OEL-1985
  src/components/bcl-carousel/__snapshots__/carousel.test.js.snap
  src/components/bcl-carousel/carousel.html.twig
  src/components/bcl-carousel/carousel.test.js
  src/compositions/bcl-gallery/__snapshots__/gallery.test.js.snap
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
Labels: tag: bug fix, process: review needed

#450 feat(documentation): Updated parameters documentation - OEL-2022
  src/components/bcl-breadcrumb/breadcrumb.html.twig
  src/components/bcl-button-group/button-group.html.twig
  src/components/bcl-button/button.html.twig
  src/components/bcl-card/card.html.twig
  src/components/bcl-carousel/carousel.html.twig
  src/components/bcl-form/form.html.twig
  src/components/bcl-icon/icon.html.twig
  src/components/bcl-modal/modal.html.twig
  src/components/bcl-pagination/pagination.html.twig
  src/components/bcl-placeholder/placeholder.html.twig
  src/components/bcl-select/select.html.twig
  src/components/bcl-textarea/textarea.html.twig
  src/components/bcl-toasts/toasts.html.twig
  src/compositions/bcl-base-templates/listing-page.html.twig
  src/compositions/bcl-colors/colors.html.twig
  src/compositions/bcl-content-banner/content-banner.html.twig
  src/compositions/bcl-date-block/date-block.html.twig
  src/compositions/bcl-fact-figures/fact-figures.html.twig
  src/compositions/bcl-featured-media/featured-media.html.twig
  src/compositions/bcl-file/file.html.twig
  src/compositions/bcl-header/header.html.twig
  src/compositions/bcl-language-switcher/language-switcher.html.twig
  src/compositions/bcl-listing/listing.html.twig
  src/compositions/bcl-project-status/project-contributions.html.twig
  src/compositions/bcl-project/project-lists.html.twig
  src/compositions/bcl-subscription-block/subscription-block.html.twig
  src/compositions/bcl-subscription/subscription-modal.html.twig
  src/compositions/bcl-user/user-compact.html.twig
Labels: tag: enhancement, process: review needed

#457 chore(deps): updates, audit fix
  builder/package.json
  package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal

#456 feat(world-flags): Providing svg sources from flag-icons package - OEL-1991
  src/themes/default/bcl-builder.config.js
  src/themes/default/package.json
  src/themes/joinup/bcl-builder.config.js
  src/themes/joinup/package.json
  src/themes/ucpkn/bcl-builder.config.js
  src/themes/ucpkn/package.json
  yarn.lock
Labels: tag: enhancement

#458 feat(timeline): Refactored timeline - OEL-2041
  src/compositions/bcl-timeline/__snapshots__/timeline.test.js.snap
  src/compositions/bcl-timeline/package.json
  src/compositions/bcl-timeline/timeline-item.html.twig
  src/compositions/bcl-timeline/timeline.html.twig
  src/compositions/bcl-timeline/timeline.test.js
Labels: tag: enhancement

#455 feat(content-banner): Redone column classes on content-banner - OEL-2038
  src/compositions/bcl-base-templates/content-type.html.twig
  src/compositions/bcl-contact-form/__snapshots__/contact-form.test.js.snap
  src/compositions/bcl-content-banner/__snapshots__/content-banner.test.js.snap
  src/compositions/bcl-content-banner/content-banner.html.twig
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-glossary/__snapshots__/glossary.test.js.snap
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-page/__snapshots__/page.test.js.snap
  src/compositions/bcl-person/__snapshots__/person.test.js.snap
  src/compositions/bcl-procurement/__snapshots__/procurement.test.js.snap
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-publication/__snapshots__/publication.test.js.snap
  src/compositions/bcl-subscription/__snapshots__/subscription.test.js.snap
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/compositions/bcl-vacancy/__snapshots__/vacancy.test.js.snap
  src/themes/default/src/scss/base/_layout.scss
Labels: tag: enhancement, process: review needed

#459 feat(file): Template for translation - OEL-2043
  src/components/bcl-pagination/pagination.html.twig
  src/compositions/bcl-file/__snapshots__/file.test.js.snap
  src/compositions/bcl-file/file-translations.html.twig
  src/compositions/bcl-file/file.html.twig
  src/compositions/bcl-file/file.test.js
Labels: tag: enhancement

#461 chore(deps): Updates 23-09-22
  builder/package.json
  package.json
  src/data/icon/package.json
  src/themes/default/package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/package.json
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal

#460 feat(gallery): Template splitting item and modal - OEL-2049
  src/compositions/bcl-gallery/__snapshots__/gallery.test.js.snap
  src/compositions/bcl-gallery/data/data.js
  src/compositions/bcl-gallery/gallery-item.html.twig
  src/compositions/bcl-gallery/gallery-modal.html.twig
  src/compositions/bcl-gallery/gallery.html.twig
  src/compositions/bcl-gallery/gallery.test.js
  src/compositions/bcl-gallery/package.json
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/themes/default/src/scss/_gallery.scss
Labels: tag: enhancement

#447 feat(description-list): Description List refactor - OEL-2014
  src/compositions/bcl-description-list/__snapshots__/description-list.test.js.snap
  src/compositions/bcl-description-list/data/data--horizontal.js
  src/compositions/bcl-description-list/data/data.js
  src/compositions/bcl-description-list/description-list-details.html.twig
  src/compositions/bcl-description-list/description-list-title.html.twig
  src/compositions/bcl-description-list/description-list.html.twig
  src/compositions/bcl-description-list/description-list.story.js
  src/compositions/bcl-description-list/description-list.test.js
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-event/data/data--details.js
  src/compositions/bcl-procurement/__snapshots__/procurement.test.js.snap
  src/compositions/bcl-procurement/data/data--sidebar-details.js
  src/compositions/bcl-project-status/__snapshots__/project-status.test.js.snap
  src/compositions/bcl-project-status/data/data--contributions.js
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-project/data/data--lists.js
  src/compositions/bcl-project/data/ucpkn/data--lists.js
  src/compositions/bcl-vacancy/__snapshots__/vacancy.test.js.snap
  src/compositions/bcl-vacancy/data/data--sidebar-details.js
  src/themes/default/src/scss/base/_utilities.scss
Labels: tag: enhancement

#463 feat(glossary): Iteration on the component styles - OEL-2007
  src/components/bcl-pagination/__snapshots__/pagination.test.js.snap
  src/components/bcl-pagination/pagination.html.twig
  src/compositions/bcl-glossary/__snapshots__/glossary.test.js.snap
  src/compositions/bcl-glossary/data/data--glossary.js
  src/compositions/bcl-glossary/data/data--listing.js
  src/compositions/bcl-glossary/glossary-listing.html.twig
  src/themes/default/src/scss/_pagination.scss
  yarn.lock
Labels: tag: enhancement

#468 fix(pagination): Fixing the way the bcl-glossary class is added - OEL-2064
  src/components/bcl-pagination/pagination.html.twig
Labels: tag: enhancement, process: review needed

#471 chore(deps): Updates 29-09-22
  builder/package.json
  package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal
