Repository openeuropa/bootstrap-component-library, pull requests merged in 2022-01, with the labels that each got.

#196 feat(accessibility): Header report - OEL-933
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-header/__snapshots__/header.test.js.snap
  src/compositions/bcl-landing-page/__snapshots__/landing-page.test.js.snap
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-page/__snapshots__/page.test.js.snap
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/data/header/data--neutral.js
  src/data/header/data--simple.js
  src/data/header/data-ec.js
  src/data/header/data-ucpkn.js
  src/data/header/data.js
  src/themes/default/src/scss/_header.scss
Labels: tag: new feature

#192 feat(accessibility): Progress report - OEL-923
  src/components/bcl-progress/__snapshots__/progress.test.js.snap
  src/components/bcl-progress/progress.html.twig
Labels: tag: new feature, process: review needed

#193 feat(accessibility): Scrollspy report - OEL-924
  src/components/bcl-scrollspy/navScrollspy.html
Labels: tag: new feature, tag: enhancement

#194 feat(accessibility): Toasts report - OEL-925
  src/components/bcl-toasts/__snapshots__/toasts.test.js.snap
  src/components/bcl-toasts/toasts.html.twig
Labels: tag: enhancement

#195 feat(accessibility): Add new brand-darker variable to JOINUP for btn and badge. - ISAICP-6870
  src/themes/joinup/src/scss/_badges.scss
  src/themes/joinup/src/scss/_buttons.scss
  src/themes/joinup/src/scss/base/_variables.scss
  src/themes/joinup/src/scss/oe-bcl-joinup.scss
Labels: process: review needed

#191 feat(accessibility): Pagination icons report - OEL-922
  src/components/bcl-pagination/__snapshots__/pagination.test.js.snap
  src/components/bcl-pagination/pagination.html.twig
  src/data/pagination/dataCustomIcons.js
Labels: tag: enhancement

#197 feat(accessibility): Search-form report - OEL-940
  src/compositions/bcl-search-form/__snapshots__/search-form.test.js.snap
  src/compositions/bcl-search-form/dataSearchSubmit.js
Labels: tag: enhancement

#198 feat(accessibility): Featured media report - OEL-947
  src/compositions/bcl-featured-media/__snapshots__/featured-media.test.js.snap
  src/compositions/bcl-featured-media/dataImage.js
Labels: tag: enhancement

#200 feat(accessibility): Users report - OEL-941
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/compositions/bcl-user/data-user-edit.js
  src/compositions/bcl-user/data-user-listing.js
  src/compositions/bcl-user/user-view.html.twig
Labels: tag: enhancement

#202 feat(accessibility): Facts and figures report - OEL-929
  src/compositions/bcl-fact-figures/__snapshots__/fact-figures.test.js.snap
  src/compositions/bcl-fact-figures/data/data.js
  src/compositions/bcl-fact-figures/fact-figures.html.twig
  src/compositions/bcl-fact-figures/fact-figures.story.js
Labels: tag: enhancement, process: review needed

#199 feat(accessibility): Group report - OEL-929
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-group/data.js
  src/compositions/bcl-group/dataLanding.js
  src/compositions/bcl-group/dataList.js
  src/compositions/bcl-group/dataListContent.js
  src/compositions/bcl-group/dataListMember.js
  src/compositions/bcl-landing-page/__snapshots__/landing-page.test.js.snap
  src/compositions/bcl-page/__snapshots__/page.test.js.snap
  src/data/header/data--simple.js
Labels: tag: enhancement

#201 feat(accessibility): Recent activities, search, news-listing report - OEL-937
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-news/data/data_listing.js
  src/compositions/bcl-recent-activities/__snapshots__/recent-activities.test.js.snap
  src/compositions/bcl-recent-activities/data.js
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-search/dataSearch.js
  src/data/header/data--no-form.js
Labels: tag: enhancement

#203 feat(accessibility): Landing page, timeline report report - OEL-952
  src/compositions/bcl-landing-page/__snapshots__/landing-page.test.js.snap
  src/compositions/bcl-landing-page/data.js
  src/compositions/bcl-timeline/__snapshots__/timeline.test.js.snap
  src/compositions/bcl-timeline/dataDefault.js
Labels: tag: enhancement, process: review needed

#190 feat(accessibility): Navigation tabs report - OEL-921
  src/components/bcl-navigation/__snapshots__/navigation.test.js.snap
  src/components/bcl-navigation/navigation.html.twig
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/data/navigation/dataTabs.js
Labels: tag: new feature, process: review needed

#206 feat(footer): EU footer report - OEL-928
  src/themes/default/src/scss/_footer.scss
  src/themes/default/src/scss/_variables.scss
Labels: tag: enhancement

#205 feat(navbar): Navbar margins - OEL-963
  src/themes/default/src/scss/_header.scss
  src/themes/default/src/scss/_variables.scss
Labels: tag: new feature, process: review needed

#209 fix(joinup): Fix custom utilities - ISAICP-6604
  src/themes/joinup/src/scss/base/_utilities.scss
Labels: tag: bug fix, process: review needed

#211 chore(deps): Green and orange updates - 10-01-22
  builder/package.json
  package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal

#213 fix(event): Review image display on event content types - OEL-992
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-event/event.html.twig
Labels: tag: bug fix

#215 fix(page): Remove card titles top margin - OEL-933
  src/compositions/bcl-page/data/data-listing--default.js
Labels: tag: bug fix

#217 fix(breadcrumb): Remove left padding on mobile - OEL-1008
  src/themes/default/src/scss/_breadcrumb.scss
Labels: tag: enhancement, process: review needed

#219 fix(headers): Review mobile alignement of language and login icons - OEL-1009
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-header/__snapshots__/header.test.js.snap
  src/compositions/bcl-landing-page/__snapshots__/landing-page.test.js.snap
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-page/__snapshots__/page.test.js.snap
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/data/header/data--neutral.js
  src/data/header/data--no-form.js
  src/data/header/data--simple.js
  src/data/header/data-ec.js
  src/data/header/data.js
Labels: process: under review, tag: bug fix

#220 fix(inpage-navigation): Review spacing for the sub-items - OEL-1010
  src/themes/default/src/scss/_inpage-navigation.scss
Labels: tag: enhancement

#221 feat(featured-media): Add default border radius - OEL-1011
  src/compositions/bcl-featured-media/__snapshots__/featured-media.test.js.snap
  src/compositions/bcl-featured-media/featured-media.html.twig
  src/compositions/bcl-landing-page/__snapshots__/landing-page.test.js.snap
Labels: tag: enhancement, process: review needed

#218 feat(color-overwrite): Fix for color variables overwrite - OEL-893
  src/themes/default/src/scss/base/_utilities.scss
  src/themes/default/src/scss/base/_variables.scss
  src/themes/default/src/scss/oe-bcl-default.scss
  src/themes/joinup/src/scss/base/_colors.scss
  src/themes/joinup/src/scss/base/_variables.scss
  src/themes/joinup/src/scss/oe-bcl-joinup.scss
  src/themes/ucpkn/src/scss/base/_colors.scss
  src/themes/ucpkn/src/scss/base/_variables.scss
  src/themes/ucpkn/src/scss/oe-bcl-ucpkn.scss
Labels: tag: enhancement

#223 feat(banner): Redone paddings on banner - OEL-1013
  src/compositions/bcl-content-banner/__snapshots__/content-banner.test.js.snap
  src/compositions/bcl-content-banner/content-banner.html.twig
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-page/data/data-listing--default.js
Labels: tag: enhancement

#224 fix(landing-page): Use full_width banner - OEL-1012
  src/compositions/bcl-landing-page/__snapshots__/landing-page.test.js.snap
  src/compositions/bcl-landing-page/data.js
Labels: tag: bug fix

#212 feat(date-block): Revamp composition - OEL-988
  src/compositions/bcl-date-block/__snapshots__/date-block.test.js.snap
  src/compositions/bcl-date-block/date-block.html.twig
  src/compositions/bcl-listing/__snapshots__/listing.test.js.snap
  src/themes/default/src/scss/base/_utilities.scss
Labels: tag: enhancement

#226 fix(featured-media): Fix spacing on mobile - OEL-1028
  src/compositions/bcl-featured-media/__snapshots__/featured-media.test.js.snap
  src/compositions/bcl-featured-media/featured-media.html.twig
Labels: tag: bug fix, process: review needed

#225 fix(header): Review button display and icon alignement - OEL-1023
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-header/__snapshots__/header.test.js.snap
  src/compositions/bcl-landing-page/__snapshots__/landing-page.test.js.snap
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-page/__snapshots__/page.test.js.snap
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-search/dataSearch.js
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/data/header/data--neutral.js
  src/data/header/data--simple.js
  src/data/header/data-ec.js
  src/data/header/data-ucpkn.js
  src/data/header/data.js
  src/themes/default/src/scss/_button.scss
  src/themes/default/src/scss/_icon.scss
  src/themes/default/src/scss/oe-bcl-default.scss
  src/themes/joinup/src/scss/oe-bcl-joinup.scss
  src/themes/ucpkn/src/scss/oe-bcl-ucpkn.scss
Labels: tag: enhancement

#214 feat(colors): Update color palette (variables) - OEL-989
  src/components/bcl-badge/__snapshots__/badge.test.js.snap
  src/components/bcl-badge/badge.html.twig
  src/components/bcl-form/__snapshots__/form.test.js.snap
  src/components/bcl-navigation/__snapshots__/navigation.test.js.snap
  src/compositions/bcl-event/data/data-listing.js
  src/compositions/bcl-event/event.story.js
  src/compositions/bcl-event/event.test.js
  src/data/form/data-disabled.js
  src/data/navigation/dataCustom.js
  src/themes/default/src/scss/base/_colors.scss
  src/themes/default/src/scss/base/_variables.scss
  src/themes/default/src/scss/oe-bcl-default.scss
  src/themes/joinup/src/scss/oe-bcl-joinup.scss
  src/themes/ucpkn/src/scss/oe-bcl-ucpkn.scss
Labels: tag: enhancement

#228 feat(border-radius): Fix border-radius for recent activities and links block - OEL-1031
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-links-block/__snapshots__/links-block.test.js.snap
  src/compositions/bcl-links-block/links-block.html.twig
  src/compositions/bcl-recent-activities/__snapshots__/recent-activities.test.js.snap
  src/compositions/bcl-recent-activities/recent-activities.html.twig
Labels: tag: enhancement

#227 feat(cards): Fix for cards border - OEL-1029
  src/components/bcl-card-layout/__snapshots__/card-layout.test.js.snap
  src/components/bcl-card/__snapshots__/card.test.js.snap
  src/components/bcl-card/card.html.twig
  src/compositions/bcl-content-banner/__snapshots__/content-banner.test.js.snap
  src/compositions/bcl-file/__snapshots__/file.test.js.snap
  src/compositions/bcl-file/file.html.twig
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-listing/__snapshots__/listing.test.js.snap
  src/compositions/bcl-listing/data/listing--default-1-col.js
  src/compositions/bcl-listing/data/listing--default-2-col.js
  src/compositions/bcl-listing/data/listing--default-3-col.js
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
Labels: tag: enhancement

#229 feat(accessibility): Disable unnecessary rules - OEL-946
  src/components/bcl-form/__snapshots__/form.test.js.snap
  src/components/bcl-select/select.story.js
  src/compositions/bcl-featured-media/featured-media.story.js
  src/compositions/bcl-group/group.story.js
  src/compositions/bcl-landing-page/landing-page.story.js
  src/compositions/bcl-page/page.story.js
  src/compositions/bcl-search/search.story.js
  src/compositions/bcl-user/user.story.js
  src/data/form/data-inline.js
  src/themes/default/storybook/.storybook/preview.js
Labels: tag: new feature, process: review needed

#237 chore(deps): updates - 24 01 22
  builder/package.json
  package.json
  src/data/icon/package.json
  src/themes/default/package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/package.json
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal

#235 fix(button): Center align button label by default - OEL-1058
  src/themes/default/src/scss/_button.scss
Labels: tag: bug fix, process: review needed

#232 feat(contact-form): Adding examples - OEL-1055
  src/components/bcl-alert/__snapshots__/alert.test.js.snap
  src/components/bcl-alert/alert.html.twig
  src/components/bcl-form/form.html.twig
  src/components/bcl-twig-templates/package.json
  src/compositions/bcl-base-templates/content-type.html.twig
  src/compositions/bcl-contact-form/.npmignore
  src/compositions/bcl-contact-form/__snapshots__/contact-form.test.js.snap
  src/compositions/bcl-contact-form/contact-form.html.twig
  src/compositions/bcl-contact-form/contact-form.story.js
  src/compositions/bcl-contact-form/contact-form.test.js
  src/compositions/bcl-contact-form/data/data-banner.js
  src/compositions/bcl-contact-form/data/data-error.js
  src/compositions/bcl-contact-form/data/data-form-error.js
  src/compositions/bcl-contact-form/data/data-form.js
  src/compositions/bcl-contact-form/data/data-success.js
  src/compositions/bcl-contact-form/package.json
Labels: tag: new feature

#240 feat(accordion): Added accordion title_tag - OEL-1071
  src/components/bcl-accordion/__snapshots__/accordion.test.js.snap
  src/components/bcl-accordion/accordion.html.twig
  src/components/bcl-accordion/accordion.test.js
  src/data/accordion/dataCustomTags.js
Labels: tag: new feature

#231 chore(themes): Align scss for joinup and ucpkn themes - OEL-1030
  src/themes/joinup/src/scss/oe-bcl-joinup.scss
  src/themes/ucpkn/src/scss/oe-bcl-ucpkn.scss
Labels: tag: bug fix

#236 chore(versions): Adding badges
  .storybook/main.js
  .storybook/preview.js
  src/compositions/bcl-contact-form/contact-form.story.js
  src/compositions/bcl-event/event.story.js
  src/compositions/bcl-group/group.story.js
  src/compositions/bcl-landing-page/landing-page.story.js
  src/compositions/bcl-news/news.story.js
  src/compositions/bcl-page/page.story.js
  src/compositions/bcl-search/search.story.js
  src/compositions/bcl-user/user.story.js
  src/themes/default/storybook/.storybook/main.js
  src/themes/default/storybook/.storybook/preview.js
  src/themes/default/storybook/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal

#241 chore(deps): updates 26-01-22
  builder/package.json
  src/data/icon/package.json
  src/themes/default/package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/package.json
  src/themes/ucpkn/package.json
  yarn.lock
Labels: tag: internal

#238 feat(blockquote): Blockquote new design - OEL-1064
  src/components/bcl-blockquote/__snapshots__/blockquote.test.js.snap
  src/components/bcl-blockquote/blockquote.html.twig
  src/components/bcl-blockquote/blockquote.story.js
Labels: tag: new feature

#230 feat(project): Adding examples - OEL-1048
  src/components/bcl-progress/progress.html.twig
  src/components/bcl-twig-templates/package.json
  src/compositions/bcl-description-list/__snapshots__/description-list.test.js.snap
  src/compositions/bcl-description-list/data.js
  src/compositions/bcl-description-list/dataHorizontal.js
  src/compositions/bcl-description-list/description-list.html.twig
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-listing/listing.html.twig
  src/compositions/bcl-project-status/.npmignore
  src/compositions/bcl-project-status/__snapshots__/project-status.test.js.snap
  src/compositions/bcl-project-status/data/data--closed.js
  src/compositions/bcl-project-status/data/data--ongoing.js
  src/compositions/bcl-project-status/data/data--planned.js
  src/compositions/bcl-project-status/package.json
  src/compositions/bcl-project-status/project-status.html.twig
  src/compositions/bcl-project-status/project-status.test.js
  src/compositions/bcl-project/.npmignore
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-project/data/data--chart.js
  src/compositions/bcl-project/data/data.js
  src/compositions/bcl-project/data/data_extra_details.js
  src/compositions/bcl-project/data/data_listing.js
  src/compositions/bcl-project/package.json
  src/compositions/bcl-project/project.html.twig
  src/compositions/bcl-project/project.story.js
  src/compositions/bcl-project/project.test.js
  tools/story-utils/index.js
Labels: tag: new feature

#242 chore(deps): Updates 31-01-22
  builder/package.json
  package.json
  src/data/icon/package.json
  src/themes/default/package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/package.json
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal

#234 feat(event): Revamp to v1.1 - OEL-1056
  src/compositions/bcl-description-list/__snapshots__/description-list.test.js.snap
  src/compositions/bcl-description-list/data.js
  src/compositions/bcl-description-list/dataHorizontal.js
  src/compositions/bcl-description-list/description-list.html.twig
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-event/data/data-page.js
  src/compositions/bcl-event/data/event-sidebar.js
  src/compositions/bcl-event/event.html.twig
  src/compositions/bcl-event/event.story.js
  src/compositions/bcl-event/event.test.js
  src/compositions/bcl-file/__snapshots__/file.test.js.snap
  src/compositions/bcl-file/file.html.twig
  src/compositions/bcl-page/__snapshots__/page.test.js.snap
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/themes/default/src/scss/_icon.scss
Labels: tag: enhancement
