Repository openeuropa/bootstrap-component-library, pull requests merged in 2022-06, with the labels that each got.

#368 feat(comments): Updated comments - OEL-1671
  src/components/bcl-accordion/accordion.html.twig
  src/components/bcl-alert/alert.html.twig
  src/components/bcl-badge/badge.html.twig
  src/components/bcl-blockquote/blockquote.html.twig
  src/components/bcl-breadcrumb/breadcrumb.html.twig
  src/components/bcl-button-group/button-group.html.twig
  src/components/bcl-button/button.html.twig
  src/components/bcl-card-layout/card-layout.html.twig
  src/components/bcl-card/card.html.twig
  src/components/bcl-carousel/carousel.html.twig
  src/components/bcl-dropdown/dropdown.html.twig
  src/components/bcl-form-input/form-input.html.twig
  src/components/bcl-form/form.html.twig
  src/components/bcl-heading/heading.html.twig
  src/components/bcl-icon/icon.html.twig
  src/components/bcl-link/link.html.twig
  src/components/bcl-list-group/list-group.html.twig
  src/components/bcl-modal/modal.html.twig
  src/components/bcl-navbar/navbar.html.twig
  src/components/bcl-navigation/navigation.html.twig
  src/components/bcl-offcanvas/__snapshots__/offcanvas.test.js.snap
  src/components/bcl-offcanvas/offcanvas.html.twig
  src/components/bcl-pagination/pagination.html.twig
  src/components/bcl-placeholder/placeholder.html.twig
  src/components/bcl-progress/progress.html.twig
  src/components/bcl-select/select.html.twig
  src/components/bcl-spinner/spinner.html.twig
  src/components/bcl-table/table.html.twig
  src/components/bcl-textarea/textarea.html.twig
  src/components/bcl-toasts/toasts.html.twig
  src/compositions/bcl-banner/banner.html.twig
  src/compositions/bcl-file/file.html.twig
  src/compositions/bcl-footer/footer.html.twig
  src/compositions/bcl-gallery/gallery.html.twig
  src/compositions/bcl-header/header.html.twig
  src/compositions/bcl-inpage-navigation/inpage-navigation.html.twig
  src/compositions/bcl-language-list/language-list-grid.html.twig
  src/compositions/bcl-links-block/links-block.html.twig
  src/compositions/bcl-listing/listing.html.twig
  src/compositions/bcl-project-status/project-status.html.twig
  src/compositions/bcl-search-form/search-form.html.twig
  src/compositions/bcl-subscription-block/subscription-block.html.twig
  src/compositions/bcl-timeline/timeline.html.twig
Labels: tag: enhancement, process: review needed

#370 chore(deps): Storybook 6.5.7
  builder/package.json
  package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/package.json
  tools/plugins/storybook-addon-code/package.json
  yarn.lock
Labels: tag: internal

#369 feat(badges): Changes to badges - OEL-1674
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-event/data/data--page.js
  src/compositions/bcl-project-status/__snapshots__/project-status.test.js.snap
  src/compositions/bcl-project-status/data/data--ongoing.js
  src/compositions/bcl-project-status/data/data--planned.js
  src/compositions/bcl-project-status/project-status.html.twig
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-project/data/data--listing.js
  src/compositions/bcl-vacancy/__snapshots__/vacancy.test.js.snap
  src/compositions/bcl-vacancy/data/data--closed-banner.js
  src/compositions/bcl-vacancy/data/data--listing.js
  src/compositions/bcl-vacancy/data/data--open-banner.js
Labels: tag: enhancement

#367 feat(facts-figures): Title font-weight - OEL-1644
  src/compositions/bcl-fact-figures/__snapshots__/fact-figures.test.js.snap
  src/compositions/bcl-fact-figures/fact-figures.html.twig
Labels: tag: enhancement

#371 feat(icons-list): Adding a page displaying all the available icons - OEL-1684
  src/compositions/bcl-colors/colors.story.js
  src/compositions/bcl-icons-list/icons-list.html.twig
  src/compositions/bcl-icons-list/icons-list.story.js
  src/compositions/bcl-icons-list/package.json
Labels: tag: new feature, process: review needed

#374 chore(deps): storybook, ecl and a few others updates
  builder/package.json
  package.json
  src/data/icon/package.json
  src/themes/default/package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/package.json
  src/themes/ucpkn/storybook/package.json
  tools/plugins/storybook-addon-code/package.json
  yarn.lock
Labels: tag: internal

#377 chore(deps): Updates - 14-06-22
  package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/package.json
  tools/plugins/storybook-addon-code/package.json
  yarn.lock
Labels: tag: internal

#375 feat(events): Adding time information, aligning with figma mockup, adding controls - OEL-1695
  package.json
  src/components/bcl-card/card.html.twig
  src/compositions/bcl-contact-form/__snapshots__/contact-form.test.js.snap
  src/compositions/bcl-content-banner/__snapshots__/content-banner.test.js.snap
  src/compositions/bcl-content-banner/content-banner.html.twig
  src/compositions/bcl-content-banner/data/data--simple.js
  src/compositions/bcl-content-banner/data/data--title.js
  src/compositions/bcl-content-banner/data/data.js
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-event/data/data--details.js
  src/compositions/bcl-event/data/data--page.js
  src/compositions/bcl-event/data/data.js
  src/compositions/bcl-event/event.story.js
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-listing/__snapshots__/listing.test.js.snap
  src/compositions/bcl-listing/data/listing--date.js
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-page/__snapshots__/page.test.js.snap
  src/compositions/bcl-person/__snapshots__/person.test.js.snap
  src/compositions/bcl-procurement/__snapshots__/procurement.test.js.snap
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-publication/__snapshots__/publication.test.js.snap
  src/compositions/bcl-subscription/__snapshots__/subscription.test.js.snap
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/compositions/bcl-vacancy/__snapshots__/vacancy.test.js.snap
  src/themes/default/src/scss/_description_list.scss
  src/themes/default/src/scss/base/_utilities.scss
  src/themes/default/src/scss/oe-bcl-default.scss
  src/themes/joinup/src/scss/oe-bcl-joinup.scss
  src/themes/ucpkn/src/scss/oe-bcl-ucpkn.scss
Labels: tag: enhancement

#381 chore(deps): Updates - 17-06-22
  package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/package.json
  tools/plugins/storybook-addon-code/package.json
  yarn.lock
Labels: tag: internal

#379 feat(flags): Adding country flags svgs to each theme - OEL-1699
  src/themes/default/bcl-builder.config.js
  src/themes/default/package.json
  src/themes/joinup/bcl-builder.config.js
  src/themes/joinup/package.json
  src/themes/ucpkn/bcl-builder.config.js
  src/themes/ucpkn/package.json
  yarn.lock
Labels: tag: new feature, process: review needed

#372 feat(title): Title harmonized - OEL-1685
  src/components/bcl-alert/__snapshots__/alert.test.js.snap
  src/components/bcl-alert/alert.html.twig
  src/components/bcl-offcanvas/offcanvas.html.twig
  src/components/bcl-pagination/__snapshots__/pagination.test.js.snap
  src/compositions/bcl-base-templates/content-type.html.twig
  src/compositions/bcl-contact-form/__snapshots__/contact-form.test.js.snap
  src/compositions/bcl-contact-form/data/data--form-error.js
  src/compositions/bcl-contact-form/data/data--form.js
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-inpage-navigation/__snapshots__/inpage-navigation.test.js.snap
  src/compositions/bcl-inpage-navigation/data/data.js
  src/compositions/bcl-inpage-navigation/inpage-navigation.html.twig
  src/compositions/bcl-language-switcher/__snapshots__/language-switcher.test.js.snap
  src/compositions/bcl-language-switcher/data.js
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-page/__snapshots__/page.test.js.snap
  src/compositions/bcl-person/__snapshots__/person.test.js.snap
  src/compositions/bcl-person/person.html.twig
  src/compositions/bcl-procurement/__snapshots__/procurement.test.js.snap
  src/compositions/bcl-procurement/data/data--content.js
  src/compositions/bcl-procurement/data/data.js
  src/compositions/bcl-procurement/procurement.html.twig
  src/compositions/bcl-procurement/procurement.story.js
  src/compositions/bcl-procurement/procurement.test.js
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-publication/__snapshots__/publication.test.js.snap
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-subscription/__snapshots__/subscription.test.js.snap
  src/compositions/bcl-subscription/data/data--modal.js
  src/compositions/bcl-subscription/subscription.story.js
  src/compositions/bcl-timeline/__snapshots__/timeline.test.js.snap
  src/compositions/bcl-timeline/timeline.html.twig
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/compositions/bcl-user/data/data--form.js
  src/compositions/bcl-user/user.html.twig
  src/compositions/bcl-vacancy/__snapshots__/vacancy.test.js.snap
  src/compositions/bcl-vacancy/vacancy.html.twig
  src/data/pagination/data--listing.js
  src/data/pagination/data.js
  src/themes/default/src/scss/base/_layout.scss
  src/themes/default/src/scss/oe-bcl-default.scss
  src/themes/joinup/src/scss/oe-bcl-joinup.scss
  src/themes/ucpkn/src/scss/oe-bcl-ucpkn.scss
Labels: tag: enhancement

#378 feat(inpage): Flat list, removing scrollspy stories - OEL-1731
  src/components/bcl-scrollspy/groupScrollspy.html
  src/components/bcl-scrollspy/listScrollspy.html
  src/components/bcl-scrollspy/navScrollspy.html
  src/components/bcl-scrollspy/package.json
  src/components/bcl-scrollspy/scrollspy.story.js
  src/compositions/bcl-inpage-navigation/__snapshots__/inpage-navigation.test.js.snap
  src/compositions/bcl-inpage-navigation/data/data--simple.js
  src/compositions/bcl-inpage-navigation/data/data.js
  src/compositions/bcl-inpage-navigation/inpage-navigation.html.twig
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-subscription/__snapshots__/subscription.test.js.snap
  src/themes/default/src/scss/_inpage-navigation.scss
Labels: tag: enhancement, process: review needed

#382 feat(links): Visited links update - OEL-1737
  src/themes/default/src/scss/base/_colors.scss
  src/themes/default/src/scss/base/_utilities.scss
Labels: tag: enhancement, process: review needed

#380 feat(glossary): Adding glossary listing and detail - OEL-1696
  package.json
  src/components/bcl-pagination/pagination.html.twig
  src/components/bcl-twig-templates/package.json
  src/compositions/bcl-base-templates/content-type.html.twig
  src/compositions/bcl-base-templates/listing-page.html.twig
  src/compositions/bcl-glossary/__snapshots__/glossary.test.js.snap
  src/compositions/bcl-glossary/data/data--detail.js
  src/compositions/bcl-glossary/data/data--glossary.js
  src/compositions/bcl-glossary/data/data--listing.js
  src/compositions/bcl-glossary/data/data--select.js
  src/compositions/bcl-glossary/glossary-detail.html.twig
  src/compositions/bcl-glossary/glossary-listing.html.twig
  src/compositions/bcl-glossary/glossary.story.js
  src/compositions/bcl-glossary/glossary.test.js
  src/compositions/bcl-glossary/package.json
  src/themes/default/src/scss/_pagination.scss
  src/themes/default/src/scss/_tabs.scss
  src/themes/default/src/scss/base/_mixins.scss
  src/themes/default/src/scss/base/_utilities.scss
  src/themes/default/src/scss/oe-bcl-default.scss
  src/themes/joinup/src/scss/oe-bcl-joinup.scss
  src/themes/ucpkn/src/scss/oe-bcl-ucpkn.scss
  tools/story-utils/index.js
  yarn.lock
Labels: tag: new feature, process: designer approval needed

#389 chore(deps): Updating sass
  builder/package.json
  yarn.lock
Labels: tag: internal

#385 feat(inpage): Removing full_page parameter, building example in the story file - OEL-1743
  src/compositions/bcl-inpage-navigation/__snapshots__/inpage-navigation.test.js.snap
  src/compositions/bcl-inpage-navigation/data/data.js
  src/compositions/bcl-inpage-navigation/inpage-navigation.html.twig
  src/compositions/bcl-inpage-navigation/inpage-navigation.story.js
  src/compositions/bcl-inpage-navigation/package.json
  yarn.lock
Labels: tag: enhancement

#387 feat(file): Updated file card variant - OEL-1691
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-file/__snapshots__/file.test.js.snap
  src/compositions/bcl-file/data/data--card.js
  src/compositions/bcl-file/file.html.twig
  src/compositions/bcl-glossary/__snapshots__/glossary.test.js.snap
  src/compositions/bcl-page/__snapshots__/page.test.js.snap
  src/compositions/bcl-person/__snapshots__/person.test.js.snap
  src/compositions/bcl-procurement/__snapshots__/procurement.test.js.snap
  src/compositions/bcl-publication/__snapshots__/publication.test.js.snap
  src/compositions/bcl-vacancy/__snapshots__/vacancy.test.js.snap
Labels: tag: enhancement

#391 feat(figma-links): Updated features figma links - OEL-1764
  src/compositions/bcl-event/event.story.js
  src/compositions/bcl-glossary/glossary.story.js
  src/compositions/bcl-group/group.story.js
  src/compositions/bcl-multilingual/multilingual.story.js
  src/compositions/bcl-news/news.story.js
  src/compositions/bcl-page/page.story.js
  src/compositions/bcl-person/person.story.js
  src/compositions/bcl-procurement/procurement.story.js
  src/compositions/bcl-project/project.story.js
  src/compositions/bcl-publication/publication.story.js
  src/compositions/bcl-search/search.story.js
  src/compositions/bcl-subscription/subscription.story.js
  src/compositions/bcl-user/user.story.js
  src/compositions/bcl-vacancy/vacancy.story.js
Labels: tag: enhancement, process: review needed

#394 chore(icons): Bringing back the bs icon sprite
  src/themes/default/bcl-builder.config.js
  src/themes/joinup/bcl-builder.config.js
  src/themes/ucpkn/bcl-builder.config.js
Labels: tag: internal, process: review needed

#395 chore(deps): Updates 29-06-22
  builder/package.json
  package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal

#396 feat(accordion): Adding optional title in the template - OEL-1793
  src/components/bcl-accordion/__snapshots__/accordion.test.js.snap
  src/components/bcl-accordion/accordion.html.twig
  src/components/bcl-accordion/accordion.test.js
Labels: tag: enhancement, process: review needed

#393 feat(description-list): Added bordered param to description-list - OEL-1777
  src/compositions/bcl-description-list/__snapshots__/description-list.test.js.snap
  src/compositions/bcl-description-list/data/data--horizontal.js
  src/compositions/bcl-description-list/description-list.html.twig
  src/compositions/bcl-description-list/description-list.story.js
  src/compositions/bcl-description-list/description-list.test.js
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-procurement/__snapshots__/procurement.test.js.snap
  src/compositions/bcl-project-status/__snapshots__/project-status.test.js.snap
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-project/project-lists.html.twig
  src/compositions/bcl-vacancy/__snapshots__/vacancy.test.js.snap
Labels: tag: enhancement

#386 feat(card-refactoring): Redone usage of card and layouts of content-banner and listings - OEL-1689
  src/components/bcl-card/__snapshots__/card.test.js.snap
  src/components/bcl-card/card.html.twig
  src/compositions/bcl-content-banner/__snapshots__/content-banner.test.js.snap
  src/compositions/bcl-content-banner/content-banner.html.twig
  src/compositions/bcl-content-banner/content-banner.story.js
  src/compositions/bcl-content-banner/data/data--page-title.js
  src/compositions/bcl-content-banner/data/data.js
  src/compositions/bcl-content-banner/test-content-banner.story.js
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-event/data/data--page.js
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-listing/__snapshots__/listing.test.js.snap
  src/compositions/bcl-listing/listing.html.twig
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-page/__snapshots__/page.test.js.snap
  src/compositions/bcl-person/__snapshots__/person.test.js.snap
  src/compositions/bcl-person/data/data--details.js
  src/compositions/bcl-procurement/__snapshots__/procurement.test.js.snap
  src/compositions/bcl-procurement/data/data--listing.js
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-publication/__snapshots__/publication.test.js.snap
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-subscription/__snapshots__/subscription.test.js.snap
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/compositions/bcl-user/data/data--form.js
  src/compositions/bcl-user/user.html.twig
  src/compositions/bcl-vacancy/__snapshots__/vacancy.test.js.snap
  src/data/card/data--horizontal.js
  src/themes/default/src/scss/base/_layout.scss
  src/themes/default/src/scss/base/_variables.scss
Labels: tag: enhancement, process: review needed

#397 feat(card): Increasing title font size - OEL-1795
  src/components/bcl-card-layout/__snapshots__/card-layout.test.js.snap
  src/components/bcl-card/__snapshots__/card.test.js.snap
  src/components/bcl-card/card.html.twig
Labels: tag: enhancement, process: review needed
