Repository openeuropa/bootstrap-component-library, pull requests merged in 2022-05, with the labels that each got.

#338 feat(spacings): Added general spacings for content banner and footer - OEL-1507
  src/compositions/bcl-base-templates/content-type.html.twig
  src/compositions/bcl-base-templates/data/content-page.js
  src/compositions/bcl-base-templates/data/layout.js
  src/compositions/bcl-contact-form/__snapshots__/contact-form.test.js.snap
  src/compositions/bcl-contact-form/contact-form.story.js
  src/compositions/bcl-contact-form/contact-form.test.js
  src/compositions/bcl-content-banner/__snapshots__/content-banner.test.js.snap
  src/compositions/bcl-content-banner/content-banner.html.twig
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-event/event.story.js
  src/compositions/bcl-event/event.test.js
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-group/data/data--landing.js
  src/compositions/bcl-group/group.story.js
  src/compositions/bcl-landing-page/__snapshots__/landing-page.test.js.snap
  src/compositions/bcl-landing-page/landing-page.story.js
  src/compositions/bcl-links-block/data/data--share.js
  src/compositions/bcl-multilingual/multilingual.story.js
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-news/news.story.js
  src/compositions/bcl-news/news.test.js
  src/compositions/bcl-page/__snapshots__/page.test.js.snap
  src/compositions/bcl-page/page.story.js
  src/compositions/bcl-person/__snapshots__/person.test.js.snap
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-project/project.story.js
  src/compositions/bcl-project/project.test.js
  src/compositions/bcl-publication/__snapshots__/publication.test.js.snap
  src/compositions/bcl-publication/publication.story.js
  src/compositions/bcl-publication/publication.test.js
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-search/search.story.js
  src/compositions/bcl-subscription/__snapshots__/subscription.test.js.snap
  src/compositions/bcl-subscription/subscription.story.js
  src/compositions/bcl-subscription/subscription.test.js
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/compositions/bcl-user/user.story.js
  src/compositions/bcl-vacancy/__snapshots__/vacancy.test.js.snap
  src/compositions/bcl-vacancy/vacancy.story.js
  src/compositions/bcl-vacancy/vacancy.test.js
  src/data/pagination/data--listing.js
  src/themes/ucpkn/src/stories/landing-page.story.js
  src/themes/ucpkn/src/stories/project.story.js
Labels: tag: enhancement

#335 feat(content-banner): Using single parameter for the action bar in content banner - OEL-1517
  src/compositions/bcl-content-banner/content-banner.html.twig
  src/compositions/bcl-content-banner/data/data.js
  src/compositions/bcl-subscription/data/data.js
  src/compositions/bcl-subscription/subscription.story.js
  src/compositions/bcl-subscription/subscription.test.js
  src/compositions/bcl-user/data/data--user-view.js
  tools/story-utils/index.js
Labels: tag: enhancement

#344 chore(deps): Updates 03-05-22
  builder/package.json
  package.json
  src/data/icon/package.json
  src/themes/default/package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/package.json
  src/themes/ucpkn/storybook/package.json
  tools/plugins/storybook-addon-code/package.json
  yarn.lock
Labels: tag: internal

#341 feat(dates): Aligning date format used in the library - OEL-1541
  src/compositions/bcl-content-banner/__snapshots__/content-banner.test.js.snap
  src/compositions/bcl-content-banner/content-banner.html.twig
  src/compositions/bcl-content-banner/content-banner.story.js
  src/compositions/bcl-content-banner/content-banner.test.js
  src/compositions/bcl-content-banner/data/data--page-title.js
  src/compositions/bcl-content-banner/data/data--simple.js
  src/compositions/bcl-content-banner/data/data.js
  src/compositions/bcl-content-banner/test-content-banner.story.js
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-event/data/data--page.js
  src/compositions/bcl-event/event.story.js
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-group/data/data--landing.js
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-person/__snapshots__/person.test.js.snap
  src/compositions/bcl-project-status/__snapshots__/project-status.test.js.snap
  src/compositions/bcl-project-status/data/data--closed.js
  src/compositions/bcl-project-status/data/data--ongoing.js
  src/compositions/bcl-project-status/data/data--planned.js
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-project/data/data--listing.js
  src/compositions/bcl-project/data/ucpkn/data--status.js
  src/compositions/bcl-project/project.story.js
  src/compositions/bcl-publication/__snapshots__/publication.test.js.snap
  src/compositions/bcl-recent-activities/__snapshots__/recent-activities.test.js.snap
  src/compositions/bcl-recent-activities/data.js
  src/compositions/bcl-recent-activities/recent-activities.html.twig
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-search/data/data--search.js
  src/compositions/bcl-search/search.story.js
  src/compositions/bcl-subscription/__snapshots__/subscription.test.js.snap
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/compositions/bcl-vacancy/__snapshots__/vacancy.test.js.snap
  src/compositions/bcl-vacancy/data/data--listing.js
Labels: tag: enhancement, process: review needed

#347 chore(deps): Updates 05-05-22
  builder/package.json
  package.json
  src/themes/joinup/package.json
  yarn.lock
Labels: tag: internal

#348 chore(deps): Updates 10-05-22
  builder/package.json
  package.json
  yarn.lock
Labels: tag: internal

#350 feat(file): Adding target=_blank to download links - OEL-1570
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-event/event.story.js
  src/compositions/bcl-file/__snapshots__/file.test.js.snap
  src/compositions/bcl-file/data/data--card.js
  src/compositions/bcl-file/data/data.js
  src/compositions/bcl-file/file.html.twig
  src/compositions/bcl-page/__snapshots__/page.test.js.snap
  src/compositions/bcl-person/__snapshots__/person.test.js.snap
  src/compositions/bcl-publication/__snapshots__/publication.test.js.snap
Labels: tag: enhancement, process: review needed

#351 chore(deps): Updates 13-05-22
  package.json
  src/themes/default/package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/package.json
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal

#349 feat(features): Updates on features to the latest version - OEL-1565
  .storybook/preview.js
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-event/data/data--page.js
  src/compositions/bcl-event/event.story.js
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-group/data/data--landing.js
  src/compositions/bcl-group/data/data--list-member.js
  src/compositions/bcl-group/data/data.js
  src/compositions/bcl-group/group.html.twig
  src/compositions/bcl-group/group.story.js
  src/compositions/bcl-group/group.test.js
  src/compositions/bcl-landing-page/landing-page.story.js
  src/compositions/bcl-listing/__snapshots__/listing.test.js.snap
  src/compositions/bcl-listing/data/listing--date.js
  src/compositions/bcl-multilingual/multilingual.story.js
  src/compositions/bcl-page/page.story.js
  src/compositions/bcl-person/__snapshots__/person.test.js.snap
  src/compositions/bcl-person/data/data--details.js
  src/compositions/bcl-person/person.html.twig
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-project/data/data--lists.js
  src/compositions/bcl-project/data/data.js
  src/compositions/bcl-project/data/ucpkn/data.js
  src/compositions/bcl-project/project.html.twig
  src/compositions/bcl-project/project.story.js
  src/compositions/bcl-project/project.test.js
  src/compositions/bcl-publication/__snapshots__/publication.test.js.snap
  src/compositions/bcl-publication/data/data.js
  src/compositions/bcl-publication/publication.html.twig
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-search/data/data--search.js
  src/compositions/bcl-search/search.html.twig
  src/compositions/bcl-subscription/subscription.story.js
  src/compositions/bcl-user/user.story.js
  src/compositions/bcl-vacancy/__snapshots__/vacancy.test.js.snap
  src/compositions/bcl-vacancy/data/data--closed-banner.js
  src/compositions/bcl-vacancy/data/data--open-banner.js
  src/compositions/bcl-vacancy/data/data.js
  src/compositions/bcl-vacancy/vacancy.html.twig
  src/compositions/bcl-vacancy/vacancy.story.js
  src/compositions/bcl-vacancy/vacancy.test.js
  src/themes/default/src/scss/base/_variables.scss
Labels: tag: enhancement

#353 chore(deps): Updates 16-05-22
  bootstrap/package.json
  builder/package.json
  package.json
  src/themes/default/package.json
  src/themes/joinup/package.json
  src/themes/ucpkn/package.json
  yarn.lock
Labels: tag: internal

#352 feat(heading): Removed font-weight bold from headings - OEL-1584
  src/components/bcl-heading/__snapshots__/heading.test.js.snap
  src/components/bcl-heading/heading.html.twig
  src/components/bcl-offcanvas/__snapshots__/offcanvas.test.js.snap
  src/components/bcl-offcanvas/offcanvas.html.twig
  src/compositions/bcl-base-templates/listing-page.html.twig
  src/compositions/bcl-contact-form/__snapshots__/contact-form.test.js.snap
  src/compositions/bcl-content-banner/__snapshots__/content-banner.test.js.snap
  src/compositions/bcl-content-banner/content-banner.html.twig
  src/compositions/bcl-description-list/__snapshots__/description-list.test.js.snap
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-event/event.html.twig
  src/compositions/bcl-fact-figures/__snapshots__/fact-figures.test.js.snap
  src/compositions/bcl-fact-figures/fact-figures.html.twig
  src/compositions/bcl-file/__snapshots__/file.test.js.snap
  src/compositions/bcl-gallery/__snapshots__/gallery.test.js.snap
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-group/group-landing.html.twig
  src/compositions/bcl-group/group.html.twig
  src/compositions/bcl-inpage-navigation/__snapshots__/inpage-navigation.test.js.snap
  src/compositions/bcl-inpage-navigation/inpage-navigation.html.twig
  src/compositions/bcl-landing-page/__snapshots__/landing-page.test.js.snap
  src/compositions/bcl-landing-page/landing-page.html.twig
  src/compositions/bcl-links-block/__snapshots__/links-block.test.js.snap
  src/compositions/bcl-links-block/data/data--share.js
  src/compositions/bcl-links-block/links-block.html.twig
  src/compositions/bcl-listing/__snapshots__/listing.test.js.snap
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-news/data/data--content.js
  src/compositions/bcl-page/__snapshots__/page.test.js.snap
  src/compositions/bcl-page/page.html.twig
  src/compositions/bcl-person/__snapshots__/person.test.js.snap
  src/compositions/bcl-person/data/data--details.js
  src/compositions/bcl-person/person.html.twig
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-project/project-lists.html.twig
  src/compositions/bcl-project/project.html.twig
  src/compositions/bcl-publication/__snapshots__/publication.test.js.snap
  src/compositions/bcl-publication/publication.html.twig
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-search/search.html.twig
  src/compositions/bcl-subscription/__snapshots__/subscription.test.js.snap
  src/compositions/bcl-timeline/__snapshots__/timeline.test.js.snap
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/compositions/bcl-user/data/data.js
  src/compositions/bcl-user/user.html.twig
  src/compositions/bcl-vacancy/__snapshots__/vacancy.test.js.snap
  src/compositions/bcl-vacancy/vacancy.html.twig
  src/themes/default/src/scss/_inpage-navigation.scss
Labels: tag: enhancement, process: review needed

#346 feat(badge): Added hover/focus state - OEL-1560
  src/components/bcl-badge/__snapshots__/badge.test.js.snap
  src/components/bcl-badge/badge.html.twig
  src/components/bcl-badge/test-badge.story.js
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-publication/__snapshots__/publication.test.js.snap
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/compositions/bcl-vacancy/__snapshots__/vacancy.test.js.snap
  src/themes/default/src/scss/_badge.scss
  src/themes/default/src/scss/base/_variables.scss
  tools/story-utils/index.js
Labels: tag: enhancement

#355 chore(deps): Updates 18-05-22
  builder/package.json
  package.json
  src/components/bcl-offcanvas/__snapshots__/offcanvas.test.js.snap
  src/data/icon/package.json
  src/themes/default/package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/package.json
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal

#357 chore(storybook): Upgrade to 6.5.0
  .storybook/main.js
  .storybook/preview.js
  builder/package.json
  package.json
  patches/@whitespace+storybook-addon-code+1.0.2.patch
  src/themes/default/storybook/.project.js
  src/themes/default/storybook/.project.json
  src/themes/default/storybook/.storybook/main.js
  src/themes/default/storybook/.storybook/manager.js
  src/themes/default/storybook/.storybook/preview.js
  src/themes/default/storybook/package.json
  src/themes/joinup/package.json
  src/themes/joinup/storybook/.project.js
  src/themes/joinup/storybook/.project.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/.project.js
  src/themes/ucpkn/storybook/.project.json
  src/themes/ucpkn/storybook/package.json
  tools/plugins/storybook-addon-code/package.json
  tools/plugins/storybook-addon-code/preset.js
  yarn.lock
Labels: tag: internal

#362 feat(button): Fix visited btns color - OEL-1625
  src/themes/default/src/scss/base/_utilities.scss
Labels: tag: bug fix, process: review needed

#365 feat(file): Fix download icon - OEL-1639
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-file/__snapshots__/file.test.js.snap
  src/compositions/bcl-file/file.html.twig
  src/compositions/bcl-page/__snapshots__/page.test.js.snap
  src/compositions/bcl-person/__snapshots__/person.test.js.snap
  src/compositions/bcl-procurement/__snapshots__/procurement.test.js.snap
  src/compositions/bcl-publication/__snapshots__/publication.test.js.snap
  src/compositions/bcl-vacancy/__snapshots__/vacancy.test.js.snap
Labels: tag: bug fix

#366 chore(deps): Updates 30-05-22
  bootstrap/package.json
  builder/package.json
  package.json
  src/data/icon/package.json
  src/themes/default/package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/package.json
  src/themes/ucpkn/storybook/package.json
  tools/plugins/storybook-addon-code/package.json
  yarn.lock
Labels: tag: internal

#364 feat(improvements): Card variant footer/header and multiselect close - OEL-1640
  src/components/bcl-card/__snapshots__/card.test.js.snap
  src/components/bcl-card/card.html.twig
  src/components/bcl-card/card.story.js
  src/themes/default/src/scss/_card.scss
  src/themes/default/src/scss/_multiselect.scss
  src/themes/default/src/scss/oe-bcl-default.scss
  src/themes/joinup/src/scss/oe-bcl-joinup.scss
  src/themes/ucpkn/src/scss/oe-bcl-ucpkn.scss
Labels: tag: enhancement
