Repository openeuropa/bootstrap-component-library, pull requests merged in 2022-03, with the labels that each got.

#275 feat(header): Added support for site name as a link in EC and EU variants - OEL-1221
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-header/__snapshots__/header.test.js.snap
  src/compositions/bcl-header/header.html.twig
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/data/header/data-ec.js
Labels: tag: enhancement

#272 chore: chromatic
  .github/workflows/chromatic.yml
  package.json
  src/components/bcl-alert/test-alert.story.js
  src/components/bcl-badge/test-badge.story.js
  src/components/bcl-blockquote/test-blockquote.story.js
  src/components/bcl-button/button.story.js
  src/components/bcl-card-layout/card-layout.story.js
  src/components/bcl-card/card.story.js
  src/components/bcl-carousel/carousel.story.js
  src/components/bcl-dropdown/dropdown.story.js
  src/components/bcl-form-input/form-input.story.js
  src/components/bcl-form/form.story.js
  src/components/bcl-link/link.story.js
  src/components/bcl-modal/modal.story.js
  src/components/bcl-offcanvas/offcanvas.story.js
  src/components/bcl-scrollspy/scrollspy.story.js
  src/compositions/bcl-content-banner/content-banner.story.js
  src/compositions/bcl-event/event.story.js
  src/compositions/bcl-featured-media/featured-media.story.js
  src/compositions/bcl-file/file.story.js
  src/compositions/bcl-group/group.story.js
  src/compositions/bcl-landing-page/landing-page.story.js
  src/compositions/bcl-listing/listing.html.twig
  src/compositions/bcl-listing/listing.story.js
  src/compositions/bcl-news/news.story.js
  src/compositions/bcl-page/page.story.js
  src/compositions/bcl-project-status/project-status.story.js
  src/compositions/bcl-project/project.story.js
  src/compositions/bcl-recent-activities/recent-activities.story.js
  src/compositions/bcl-search-form/search-form.story.js
  src/compositions/bcl-search/search.story.js
  src/compositions/bcl-subscription/subscription.story.js
  src/compositions/bcl-user/user-view-compact.html.twig
  src/compositions/bcl-user/user.story.js
  src/themes/default/storybook/.storybook/main.js
  src/themes/default/storybook/.storybook/preview.js
  src/themes/default/storybook/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal

#276 feat(icons): Added custom icons to all themes - OEL-1222
  .gitignore
  bootstrap/package.json
  builder/scripts/sprite.js
  src/components/bcl-alert/alert.story.js
  src/components/bcl-alert/test-alert.story.js
  src/components/bcl-badge/badge.story.js
  src/components/bcl-badge/test-badge.story.js
  src/components/bcl-breadcrumb/breadcrumb.story.js
  src/components/bcl-button/button.story.js
  src/components/bcl-icon/icon.story.js
  src/components/bcl-link/link.story.js
  src/components/bcl-pagination/pagination.story.js
  src/compositions/bcl-banner/banner.story.js
  src/compositions/bcl-contact-form/contact-form.story.js
  src/compositions/bcl-fact-figures/fact-figures.story.js
  src/compositions/bcl-links-block/links-block.story.js
  src/compositions/bcl-timeline/timeline.story.js
  src/themes/default/bcl-builder.config.js
  src/themes/default/package.json
  src/themes/default/src/icons/icons.js
  src/themes/default/src/scss/base/_utilities.scss
  src/themes/joinup/bcl-builder.config.js
  src/themes/joinup/package.json
  src/themes/ucpkn/bcl-builder.config.js
  src/themes/ucpkn/package.json
  src/themes/ucpkn/src/stories/landing-page.story.js
  tools/story-utils/index.js
Labels: tag: new feature, process: review needed

#283 feat(language-switcher): Added language switcher - OEL-1243
  src/components/bcl-twig-templates/package.json
  src/compositions/bcl-language-switcher/__snapshots__/language-switcher.test.js.snap
  src/compositions/bcl-language-switcher/data/data.js
  src/compositions/bcl-language-switcher/language-switcher.html.twig
  src/compositions/bcl-language-switcher/language-switcher.story.js
  src/compositions/bcl-language-switcher/language-switcher.test.js
  src/compositions/bcl-language-switcher/package.json
Labels: tag: new feature

#287 chore(deps): Updates 08-03-22
  builder/package.json
  package.json
  yarn.lock
Labels: tag: internal

#273 feat(carousel): Carousel update - OEL-1197
  src/components/bcl-carousel/__snapshots__/carousel.test.js.snap
  src/components/bcl-carousel/carousel.html.twig
  src/components/bcl-carousel/carousel.story.js
  src/components/bcl-carousel/carousel.test.js
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/data/carousel/data.js
  src/themes/default/src/scss/_carousel.scss
  src/themes/default/src/scss/oe-bcl-default.scss
  src/themes/joinup/src/scss/oe-bcl-joinup.scss
  src/themes/ucpkn/src/scss/oe-bcl-ucpkn.scss
Labels: tag: enhancement

#296 chore(deps): Updates 14-03-22
  builder/package.json
  package.json
  yarn.lock
Labels: tag: internal

#297 fix(icons): Adding missing icons for pagination
  src/themes/default/src/icons/icons.js
Labels: tag: bug fix

#299 chore(deps): Updates and dependabot alerts
  builder/package.json
  package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal

#298 feat(content-banner): Content banner update - OEL-1323
  src/compositions/bcl-contact-form/__snapshots__/contact-form.test.js.snap
  src/compositions/bcl-content-banner/__snapshots__/content-banner.test.js.snap
  src/compositions/bcl-content-banner/content-banner.html.twig
  src/compositions/bcl-content-banner/content-banner.story.js
  src/compositions/bcl-content-banner/test-content-banner.story.js
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-person/__snapshots__/project.test.js.snap
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-subscription/__snapshots__/subscription.test.js.snap
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
Labels: tag: enhancement

#302 feat(pagination): Add first and last params and fix icon alignment - OEL-1316
  src/components/bcl-pagination/__snapshots__/pagination.test.js.snap
  src/components/bcl-pagination/pagination.html.twig
  src/components/bcl-pagination/pagination.story.js
  src/components/bcl-pagination/pagination.test.js
  src/compositions/bcl-group/__snapshots__/group.test.js.snap
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-person/__snapshots__/project.test.js.snap
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-search/__snapshots__/search.test.js.snap
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/data/pagination/data--custom-icons.js
  src/data/pagination/data--listing.js
  src/data/pagination/data.js
  src/themes/default/src/icons/icons.js
  src/themes/default/src/scss/_pagination.scss
  src/themes/default/src/scss/oe-bcl-default.scss
  src/themes/joinup/src/scss/oe-bcl-joinup.scss
  src/themes/ucpkn/src/scss/oe-bcl-ucpkn.scss
Labels: tag: enhancement

#304 feat(date-block): Updated date-block - OEL-1336
  src/compositions/bcl-date-block/__snapshots__/date-block.test.js.snap
  src/compositions/bcl-date-block/data/data--end-date.js
  src/compositions/bcl-date-block/date-block.html.twig
  src/compositions/bcl-date-block/date-block.story.js
  src/compositions/bcl-date-block/date-block.test.js
  src/compositions/bcl-date-block/test-date-block.story.js
  src/compositions/bcl-listing/__snapshots__/listing.test.js.snap
  src/compositions/bcl-listing/listing.html.twig
  src/themes/default/src/scss/base/_utilities.scss
Labels: tag: enhancement, process: review needed

#306 feat(person-files): Added title for person feature files - OEL-1351
  src/compositions/bcl-person/__snapshots__/project.test.js.snap
  src/compositions/bcl-person/data/data--details.js
  src/compositions/bcl-person/person.html.twig
Labels: tag: enhancement

#307 feat(content-banner): Added links in content banner - OEL-1359
  src/components/bcl-card-layout/__snapshots__/card-layout.test.js.snap
  src/components/bcl-card/card.html.twig
  src/compositions/bcl-contact-form/__snapshots__/contact-form.test.js.snap
  src/compositions/bcl-content-banner/__snapshots__/content-banner.test.js.snap
  src/compositions/bcl-content-banner/content-banner.html.twig
  src/compositions/bcl-content-banner/content-banner.story.js
  src/compositions/bcl-content-banner/content-banner.test.js
  src/compositions/bcl-content-banner/data/data--action-button.js
  src/compositions/bcl-content-banner/data/data--links.js
  src/compositions/bcl-content-banner/data/data.js
  src/compositions/bcl-content-banner/test-content-banner.story.js
  src/compositions/bcl-event/__snapshots__/event.test.js.snap
  src/compositions/bcl-news/__snapshots__/news.test.js.snap
  src/compositions/bcl-project/__snapshots__/project.test.js.snap
  src/compositions/bcl-subscription/__snapshots__/subscription.test.js.snap
  src/compositions/bcl-user/__snapshots__/user.test.js.snap
  src/themes/default/src/icons/icons.js
Labels: tag: enhancement, process: review needed

#295 feat(gallery): Added gallery paragraph - OEL-1312
  scripts/watch.js
  src/components/bcl-carousel/__snapshots__/carousel.test.js.snap
  src/components/bcl-carousel/carousel.html.twig
  src/components/bcl-twig-templates/package.json
  src/compositions/bcl-gallery/.npmignore
  src/compositions/bcl-gallery/__snapshots__/gallery.test.js.snap
  src/compositions/bcl-gallery/data/data.js
  src/compositions/bcl-gallery/gallery.html.twig
  src/compositions/bcl-gallery/gallery.story.js
  src/compositions/bcl-gallery/gallery.test.js
  src/compositions/bcl-gallery/package.json
  src/compositions/bcl-gallery/test-gallery.story.js
  src/data/carousel/data.js
  src/themes/default/src/js/gallery/gallery.js
  src/themes/default/src/js/index.esm.js
  src/themes/default/src/js/index.umd.js
  src/themes/default/src/scss/_gallery.scss
  src/themes/default/src/scss/oe-bcl-default.scss
  src/themes/joinup/src/js/index.esm.js
  src/themes/joinup/src/js/index.umd.js
  src/themes/joinup/src/scss/oe-bcl-joinup.scss
  src/themes/ucpkn/src/js/index.esm.js
  src/themes/ucpkn/src/js/index.umd.js
  src/themes/ucpkn/src/scss/oe-bcl-ucpkn.scss
  yarn.lock
Labels: tag: new feature

#311 feat(icons): Adding icons used in the application - OEL-1348
  src/themes/default/src/icons/icons.js
Labels: tag: enhancement

#312 chore(deps): Updates 29-03-22
  builder/package.json
  package.json
  src/themes/default/storybook/package.json
  src/themes/joinup/package.json
  src/themes/joinup/storybook/package.json
  src/themes/ucpkn/storybook/package.json
  yarn.lock
Labels: tag: internal
